### ISSUE TITLE
Error When Loading Addon (on _classic_beta_)

### ISSUE THREAD

**Issue by towneh** [Wuild/GatherLite#1]
Message: Interface\AddOns\GatherLite\GatherLite.lua:30: table index is nil
Time: Fri Aug 16 01:19:43 2019
Count: 1
Stack: Interface\AddOns\GatherLite\GatherLite.lua:30: table index is nil
Interface\AddOns\GatherLite\GatherLite.lua:30: in main chunk

Locals: name = "GatherLite"
GatherLite = <table> {
 tracker = <table> {
 }
 nodeUpdated = false
 name = "GatherLite"
 needMapUpdate = false
 gatherSpellRanges = <table> {
 }
 version = "@project-version@"
}
HBD = <table> {
 mapData = <table> {
 }
 GetAllMapIDs = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:312
 UpdateCurrentPosition = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:241
 callbacks = <table> {
 }
 GetPlayerZone = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:516
 transforms = <table> {
 }
 GetLocalizedMap = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:296
 eventFrame = <unnamed> {
 }
 GetPlayerZonePosition = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:524
 GetPlayerWorldPosition = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:504
 GetZoneDistance = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:448
 GetUnitWorldPosition = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:492
 GetWorldCoordinatesFromZone = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:324
 GetWorldDistance = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:434
 GetWorldCoordinatesFromAzerothWorldMap = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:339
 GetZoneSize = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:303
 worldMapData = <table> {
 }
 UnregisterCallback = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 GetZoneCoordinatesFromWorld = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:356
 RegisterCallback = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 TranslateZoneCoordinates = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:411
 GetWorldVector = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:469
 GetAzerothWorldMapCoordinatesFromWorld = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-2.0.lua:375
}
Pins = <table> {
 minimapPins = <table> {
 }
 SetMinimapObject = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:618
 worldmapPinsPool = <table> {
 }
 RemoveMinimapIcon = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:592
 IsMinimapIconOnEdge = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:581
 Minimap = Minimap {
 }
 RemoveAllWorldMapIcons = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:730
 worldmapPins = <table> {
 }
 RemoveAllMinimapIcons = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:605
 worldmapProviderPin = <table> {
 }
 worldmapProvider = <table> {
 }
 GetVectorToIcon = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:743
 RemoveWorldMapIcon = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:718
 AddMinimapIconWorld = <function> defined @Interface\AddOns\GatherLite\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:517
 AddMinimapIconMap = <function> defined @Interface\AddOns\GatherLite\L

**Comment by towneh** [comment]
Message: Interface\AddOns\GatherLite\GatherLiteSettings.lua:162: attempt to index global 'GatherLiteConfigCharacter' (a nil value)
Time: Fri Aug 16 01:21:26 2019
Count: 1
Stack: Interface\AddOns\GatherLite\GatherLiteSettings.lua:162: attempt to index global 'GatherLiteConfigCharacter' (a nil value)
Interface\AddOns\GatherLite\GatherLiteSettings.lua:162: in function <Interface\AddOns\GatherLite\GatherLiteSettings.lua:160>

Locals: self = GatherLiteOptionsPanel {
 0 = <userdata>
 cancel = <function> defined @Interface\FrameXML\InterfaceOptionsFrame.lua:625
 name = "GatherLite"
 CheckButton = GatherLiteSharingParty {
 }
 refresh = <function> defined @Interface\FrameXML\InterfaceOptionsFrame.lua:627
 okay = <function> defined @Interface\FrameXML\InterfaceOptionsFrame.lua:624
 default = <function> defined @Interface\FrameXML\InterfaceOptionsFrame.lua:626
}
event = "ADDON_LOADED"
(*temporary) = <function> defined =[C]:-1
(*temporary) = GatherLiteWorldMapIconSize {
 0 = <userdata>
 type = 3
 Thumb = GatherLiteWorldMapIconSizeThumb {
 }
 Text = GatherLiteWorldMapIconSizeText {
 }
 High = GatherLiteWorldMapIconSizeHigh {
 }
 Low = GatherLiteWorldMapIconSizeLow {
 }
}
(*temporary) = nil
(*temporary) = "attempt to index global 'GatherLiteConfigCharacter' (a nil value)"
GatherLite = <table> {
 tracker = <table> {
 }
 nodeUpdated = false
 name = "GatherLite"
 needMapUpdate = false
 gatherSpellRanges = <table> {
 }
 version = "@project-version@"
}

**Comment by towneh** [comment]
Message: (null)
Time: Fri Aug 16 01:21:26 2019
Count: 3

**Comment by Wuild** [comment]
I think i have fixed it in the latest version i just uploaded.
Please verify if possible.

**Comment by towneh** [comment]
Yep latest clone of master has fixed it, it's now loading and recording nodes.
Is the slash command /gather or /gatherer supposed to do anything? it doesn't atm.

**Comment by Wuild** [comment]
only available slash commands are

/gather reload --- reload the maps
/gather debugging (on|off) -- turn debugging on or off
/gather reset -- resets the database

**Comment by towneh** [comment]
OK those work - I guess it would make sense to add a context list if you just type /gather for available options rather than showing nothing? Either way, issue resolved :)

**Comment by Wuild** [comment]
i probably will when i can get into classic :D
