### ISSUE TITLE
Nodes form different maps are stacking.

### ISSUE THREAD

**Issue by fsdragon** [Wuild/GatherLite#10]
Nodes are not being localized to Zone map.

**Comment by Wuild** [comment]
are you using the latest 1.0.31-classic version?

**Comment by JumpY2k3** [comment]
Same here. If someone has herbs in Tirisfal for example I see them on map. After switchting back to the barrens, the same herb coords are now in this map until I use /reload. 
So you have to fix the position of point in relation to the correct zone.

**Comment by Wuild** [comment]
ill look into it

**Comment by Wuild** [comment]
please download the latest 1.0.32 version and report back

**Comment by JumpY2k3** [comment]
It's more bugged than before :/ You need Screenshots or sth?

**Comment by Wuild** [comment]
We have noticed that an addon called Zygor guides is screwing up the map... this is nothing i can do anything about.
