### ISSUE TITLE
gatherlite.labcake.org doesn't show any fish or treasure

### ISSUE THREAD

**Issue by Djfe** [Wuild/GatherLite#100]
**Describe the bug**
https://gatherlite.labcake.org/
There are no fish and treasure listed even though I just uploaded a file containing 
162 fish and
916 treasure

**Expected behavior**
The bar diagramm should show values for those two columns as well.

**Comment by Wuild** [comment]
We're not gathering fish or treasures at this point

**Comment by Djfe** [comment]
ok thx for the answer

If you wanna make that obvious on your website, then you could hide those two columns for now :)
