### ISSUE TITLE
Nodes appear on UI while map is not open.

### ISSUE THREAD

**Issue by danbeardan** [Wuild/GatherLite#101]
**Describe the bug**
Recorded nodes appear on standard UI without map open. Disabled all other addons and issue persists.

**To Reproduce**
Gather enough nodes that they appear on UI, appears to correspond with continent that character is currently located on.

**Expected behavior**
Node images should only appear on map.

**Comment by Wuild** [comment]
I believe your using an older version of GatherLite, Please update your addon through curseforge or the twitch app. I'm not uploading this addon anywhere else and if you have gotten it from somewhere else i'm not the maintainer on that website. If this error still occures after updating your addon i will look into it once more.
