### ISSUE TITLE
p2p sharing never finishes (stuck at last syncable node)

### ISSUE THREAD

**Issue by Djfe** [Wuild/GatherLite#102]
**Describe the bug**
The sync never completes. (p2p sharing)
It's stuck one point before it finishes
https://i.imgur.com/U3HnALB.png

Also:
/reload restarts the scan and gatherer doesn't remember which nodes where already synced with whom so it keeps on trying.
I'm also wondering a bit why syncing takes so long, it's just a 3MB file after all. Is the communication channel limited? Would compression help maybe?

**Comment by Djfe** [comment]
![](https://i.imgur.com/i3DfGCq.png)

**Comment by Wuild** [comment]
this should have been fixed now.
