### ISSUE TITLE
one bruise weed isn't tracked

### ISSUE THREAD

**Issue by Djfe** [Wuild/GatherLite#103]
**Describe the bug**
https://i.imgur.com/XqFtvp6.pngm

Gatherer Lite doesn't add this bruise weed in redrige mountains to the list of discovered nodes.

**Comment by Djfe** [comment]
I closed this because I realized I have to harvest it to track it.
Now I harvested three Stranglekelp but they aren't showing up on the map.
![](https://i.imgur.com/AWrfTHF.jpg)
![](https://i.imgur.com/cG51izg.png)
![](https://i.imgur.com/6CCxcS1.jpg)

**Comment by Wuild** [comment]
this could be a map issue, not sure though check if you have "show nodes on continent map" or show on neighbor map in the settings panel

**Comment by Djfe** [comment]
I had continent map turned off, though it still doesn't show up.
![](https://i.imgur.com/4tDchg7.jpg)
![](https://i.imgur.com/UKX4tXD.jpg)

I'm on 1.3.3

**Comment by Djfe** [comment]
I just collected a yellow crystal here and it wasn't tracked
![](https://i.imgur.com/K205RsH.jpg)

this red one wasn't tracked either
https://i.imgur.com/CDo8WlQ.jpg

even with auto loot turned off it doesn't register them for me
![](https://i.imgur.com/XbLx2Ms.jpg)

ungoro soil
![](https://i.imgur.com/Nynz3ke.jpg)

other crystals were added to the existing items on the map, and I was able to add new entries for un'goro soil before
![](https://i.imgur.com/z03tAYm.jpg)

**Comment by Djfe** [comment]
This is what it says with debugging enabled:
![](https://i.imgur.com/7OldIb4.png)

still no new icon/entry on the map :/

**Comment by Djfe** [comment]
Restarting the game, the entry isn't displayed either

**Comment by Wuild** [comment]
This has been fixed in 3.0.0-alpha. Available for download now.
