### ISSUE TITLE
Icons showing up scattered on main screen

### ISSUE THREAD

**Issue by bensussman** [Wuild/GatherLite#104]
**Describe the bug**
Icons are showing up scattered on the main screen, as if they are supposed to be overlaid on a map but it's the regular play screen.

**To Reproduce**
1. Install Gatherlite (WoW Classic)
2. Collect a bunch of stuff over time
3. Open and close map a lot
4. See icons on play screen

**Expected behavior**
I would only expect icons on the minimap and on the map screen, not on the regular play screen

**Screenshots**
You can see the icons on the left half of the screen. It shows some Kingsblood and Fadeleaf etc.
![image](https://user-images.githubusercontent.com/86856/66497169-13cb7c80-ea8a-11e9-8703-fabcb09ebc56.png)

**Comment by Wuild** [comment]
I believe your using an older version of GatherLite, Please update your addon through curseforge or the twitch app. I'm not uploading this addon anywhere else and if you have gotten it from somewhere else i'm not the maintainer on that website. If this error still occures after updating your addon i will look into it once more.
