### ISSUE TITLE
A Briarthorn Node is showing up incorrectly.

### ISSUE THREAD

**Issue by TaliesinWasTaken** [Wuild/GatherLite#106]
**Describe the bug**
Instead of appearing on the minimap or full map, one of my harvested nodes is showing up on my playscreen. Interestingly, it only shows up there when I am in the Eastern Kingdoms, not in Kalimdor.

**To Reproduce**
Can't help you much here, it happened automatically when gathering a node.

**Expected behavior**
It would be nice if there was a way to remove tracked nodes, such as via right-clicking or shift-clicking them. Unfortunately there doesn't seem to be a way to get rid of this short of removing the AddOn entirely.

**Screenshots**
https://imgur.com/a/JpsbnxP

**Additional context**
The node also shows a Gromsblood, which is strange.

**Comment by pabloavenburg** [comment]
I have the same problem, but with several nodes of any type. Some of these nodes show up while I'm at Kalimdor and some others while I'm at Eastern Kingdoms. Screenshots attached.

Is there any quick way for me to fix it? I'll buy you a coffee if we can make it work. Thank you very much for your time and dedication. Let me know if there's any file or log that I can prove to help you.

![WoWScrnShot_102019_163313](https://user-images.githubusercontent.com/9995255/67165181-6a716a00-f358-11e9-9ceb-8fdd479a4e60.jpg)
![WoWScrnShot_102019_163858](https://user-images.githubusercontent.com/9995255/67165182-6a716a00-f358-11e9-880c-3f00d1544ad3.jpg)

**Comment by Wuild** [comment]
You need to update to the latest version from curseforge or the twitch app as your using a very old version of the addon

**Comment by pabloavenburg** [comment]
Thank you that fixed it
