### ISSUE TITLE
Incorrect / missing herbs

### ISSUE THREAD

**Issue by TheMEFFER** [Wuild/GatherLite#107]
**Describe the bug**
***Point of notice*** This happened in the previous version. Check "Additional context" for further explanation!

A few herbs have been looted, which either show up initially on the map and minimap and later disappear, or don't show up at all. It seems these "relocate" to other zones as parts of other herb node locations.
- This specific case is of a Black Lotus, which was looted in Winterspring this morning, at the Black Lotus spawn point located (when looking, on the map - second picture showing location): South of Mazthoril, north of Frostwhisper Gorge, and west of Owl Wing Thicket, at the Owlkin-infested cave.

Additionally, as stated initially, I have experienced Gromsblood, Dreamfoil and other herb nodes in both Felwood and EPL, that appear in the start, and then later have disappeared from the map.

**To Reproduce**
1. Go to Winterspring, at the previously mentioned spawn point (also shown in picture number 2).
2. Click on "Black Lotus".
3. Open the map, notice if the Black Lotus is there, or if it is located as part of another herbspawn, either in WPL or any other zone.
4. See "error".

**Expected behavior**
Using this addon, I would expect the herb spawn to appear where it is looted.

**Screenshots**
[Incorrect Black Lotus in WPL.](https://imgur.com/fFHcJEK)
[Location of where it was looted.](https://imgur.com/0VwhGvF)

**Additional context**
This happened in the previous version of the addon. I hadn't checked for updates prior to this occurance, so it might have been fixed already. This bug report is to assist, if this is not the case.

**Comment by Wuild** [comment]
Maybe somthing wrong with the mapID, id need more information and try this one out my self to debug it.
