### ISSUE TITLE
Overwriting database

### ISSUE THREAD

**Issue by TheMEFFER** [Wuild/GatherLite#108]
**Describe the bug**
Upon updating to the latest version, majority of my database has been randomly overwritten. Various of the new notes are even incorrect, heavily reducing the usefulness of the addon for farm-runs.

**To Reproduce**
1. Update the addon from 1.3.2 to 1.3.3, **WHILE** having another persons database than your own.

**Expected behavior**
Updating the addon should NOT overwrite my database, not even part of it. This removed timers, and even some of my notes, most notably several Black Lotus nodes.

**Screenshots**
[The only screenshot I had available pre-update, from another bug report.](https://imgur.com/0VwhGvF)
[Picture following update](https://imgur.com/fhl0KlL)

**Additional context**
While a new Black Lotus in picture 2 has been introduced, several of my previous Black Lotus have been removed from various zones. An update that overhaul my database, with the various incorrect spawns and removal of majority of my own (and thus, timers), basically requires a reset of my database.
A fix for this would be greatly appreciated, so more people updating doesn't break their addon.

**Comment by PluttenHFH** [comment]
I've had entire zones lose half their nodes, with the remaining half saying it was found by players on other servers.
And rediscovering a node that was previously marked on my map does not add an icon back, effectively making the addon useless.

EDIT: version 1.3.3

**Comment by Wuild** [comment]
Go to the settings panel and in uncheck “use predefined database”

**Comment by Wuild** [comment]
Guessing this was the issue... closing the ticket.
