### ISSUE TITLE
Game stutters with v.1.3.3-classic

### ISSUE THREAD

**Issue by Calzeru** [Wuild/GatherLite#109]
v.1.3.3-classic causes my game to have a very small ministutter every second or so. Downgraded to 1.3.2-classic and everything is fine again.

**Comment by Wuild** [comment]
Try unchecking the "use predefined database" in the settings panel

**Comment by Calzeru** [comment]
That fixed the issue. Thanks for the fast reply and a great addon!

**Comment by DevidraEX** [comment]
Is it possible to fix this without disabling?

It's nice, but if I find everything myself does it still lag so much? :(

**Comment by Wuild** [comment]
The predefined database has been removed for the time beeing. Lag should be removed along with it.
