### ISSUE TITLE
Lost Data??

### ISSUE THREAD

**Issue by Kolakhan** [Wuild/GatherLite#110]
I installed the latest Gatherlite over the one I had previously installed and lost all my data.  Can you tell me what file has the data in it that I may try to recover?

**Comment by Wuild** [comment]
your data should be lost. 
Try unchecking the "use predefined database" in the settings panel

**Comment by Vectraat69** [comment]
Updated Gatherlite the other day and went to Felwood. Noticed that at least 50% of my herbs are missing from the map and every time I gather new herbs they are no longer marked on the map from where I gathered them. What happened? Even when I de-select "Use predefined database" the herbs don't show up.

**Comment by Wuild** [comment]
This should be fixed in the latest version 2.0.0
