### ISSUE TITLE
Question about node sharing

### ISSUE THREAD

**Issue by Diabeasticles** [Wuild/GatherLite#111]
If I don't have "share nodes" enabled, will other players who have it enabled still share their nodes into my database or does it remove the feature from both "sides"?

**Comment by Wuild** [comment]
both needs to have "share nodes" enabled.

**Comment by Diabeasticles** [comment]
Ah ok,, so if only one has it enabled there won't be anything shared between the two?

And another question; if I download the latest version, will it reset my database?

Sry for being scrub.

**Comment by Wuild** [comment]
Yes
No

**Comment by Diabeasticles** [comment]
Cool, thx for the speedy answers :)

**Comment by Wuild** [comment]
just woke up so you got lucky! :)

**Comment by Diabeasticles** [comment]
goodmorning, didn't expect it to be that instant :p

**Comment by Diabeasticles** [comment]
and great addon btw, i enjoy it alot

**Comment by Wuild** [comment]
Thanks!
