### ISSUE TITLE
Blocked from an action?

### ISSUE THREAD

**Issue by Vectraat69** [Wuild/GatherLite#112]
"GatherLite has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI." ?

Ever since I updated it, I get this message and a lot of my herb spawns are missing and when I pick new herbs they don't show up on the map anymore. Did Blizzard push an update that broke this addon?

**Comment by Wuild** [comment]
This should be fixed in the latest version 2.0.0
