### ISSUE TITLE
sync issue? bugged out name

### ISSUE THREAD

**Issue by Djfe** [Wuild/GatherLite#113]
**Describe the bug**
The name of a treasure item is bugged out.
Ungoro
it's like a combination of Un'Goro-Erdhaufen and Lebenswurz.
maybe a sync failed in a weird way and corrupted this part of the db?
or a packet was corrupted
or there was an error while saving
or there is a bug in the code somewhere.

I experience disconnects from time to time and I also had freeze at least once (force reboot of my pc was needed) while playing

**Screenshots**
![](https://i.imgur.com/YCGi0Hx.jpg)

**Comment by Djfe** [comment]
according to the item it should be Lebenswurz so herbalism not treasure

This one also doesn't make any sense, you can't get mondbestrahlte feder in Un'Goro, they are a questitem from Winterspring
![](https://i.imgur.com/VJ4ZDJT.jpg)

**Comment by Djfe** [comment]
same goes for these two crystals in darnassus ^^

![](https://i.imgur.com/R5Hoyxo.jpg)
![](https://i.imgur.com/VpKzsxg.jpg)

maybe the coordinates are correct but map is wrong?

**Comment by Wuild** [comment]
This is wierd and id require more information, please upload your database here so i can take a look on what whent wrong.

**Comment by Djfe** [comment]
Sure, I hope this helps :)
[GatherLite.zip](https://github.com/Wuild/GatherLite/files/4009805/GatherLite.zip)

**Comment by Wuild** [comment]
This has been fixed in 3.0.0-alpha. Available for download now.
