### ISSUE TITLE
update item icon upon revisiting

### ISSUE THREAD

**Issue by Djfe** [Wuild/GatherLite#114]
for cases like the crystals, the icon should be updated/overwritten, upon revisiting
then it would be a treasure box from then on.
![](https://i.imgur.com/TCeB2GZ.jpg)

**Comment by Djfe** [comment]
on that note: it would be nice, if crystals, un'goro soil and Bloodpetal Sprout would have icons that are differentiable and not the same chest icon :)
though, some have the chest icon some don't.
My guess is that something was changed over time. (how the icon was selected)

**Comment by Djfe** [comment]
I just realized that some items are so close to each other, that they are "grouped" by gatherlite to one. I wouldn't know which item to show for those except the chest, but all others who are exclusive should have a recognizable item imo

**Comment by Wuild** [comment]
Different "nodes" should not be grouped... We try and find the closest node of the same type and combine them. If we would save all the nodes based on "ore type (iron or gold)" the map would be even more cluttered then it's already is.
