### ISSUE TITLE
tracked quest items - treasure

### ISSUE THREAD

**Issue by Djfe** [Wuild/GatherLite#115]
**Describe the bug**
I just read the debugging log while doing Zul'Mashar.
GatherLite doesn't add quest items to treasure.
but why is (as an example) Symbol of Lost Honor showing up on the map?:
![](https://i.imgur.com/4v5Pq8z.jpg)
Is it from an older version where quest items where still tracked?
Why does gather still increase the number of found items then (it went from 1x to 2x, when I picked it up.

**Comment by Djfe** [comment]
![](https://i.imgur.com/Sl7EJJ0.png)

**Comment by Jazzman1976** [comment]
I would also expect, that quest items are not handled as treasure items. I have also tracked all quest items as treasures on the minimap and the world map. I would like to have only real treasure items logged.

**Comment by Wuild** [comment]
Quest items should not be handled as treasure items correct... Altho in an older version this was not the case and some the items are still beeing tracked. Nothing i can do about that other then resetting your database.
