### ISSUE TITLE
Allow personal Database with server specific predefined.

### ISSUE THREAD

**Issue by LordFrz** [Wuild/GatherLite#118]
I love the idea of the predefined database but in practice it's almost useless. None of the nodes ever are there, and the few I can reliably goto are never marked. It would be nice if it used both, maybe allow me to dim the ones that I've never been too and make the ones I got to stand out on the map.

**Comment by adamk33n3r** [comment]
I also don't like that it forced them on me. I turn off the predefined database in the settings and it's still showing me everything. The reason I got this addon was so that I wasn't spoiled by things I haven't found. Now it's useless.

**Comment by adamk33n3r** [comment]
I do like the idea of combining. The personal info was nice like last visited. I think it should also be default off. The whole point of the addon was to have your own list not to just "cheat", ya know?

**Comment by Wuild** [comment]
The predefined has been removed and is beeing moved to an optional addon
