### ISSUE TITLE
Nodes not being recorded

### ISSUE THREAD

**Issue by RdmState** [Wuild/GatherLite#119]
When I gathered certain unmarked nodes, they were not being added as new nodes. I did some diging and discovered that GatherLite believes they already exist as findExistingNode and findExistingNodeLocal do not take into account the mapID the player is on. They only look for a match amongst all nodes of the same type. 

So if a node is in a similar position on a different map, it doesn't record the node for the current map. I hope this is enough information to go on to remedy the problem.

**Comment by Schoof-T** [comment]
Can confirm, I have the same issue.

**Comment by Lanessar** [comment]
Can confirm, same issue. This occurs HEAVILY in Azshara with nearly all mining nodes (rich thorium veins) throughout the Bay of Storms. Many of the Elemental Water pools are also not getting recorded as well.

**Comment by RyanBerge** [comment]
I am having this issue still with version 1.3.3.

**Comment by Djfe** [comment]
I'm having the same issue. sometimes it tracks though
#103 

I was able to record all elemental water pool nodes by now though
Though it didn't work on the first try everytime, I think?

I think development on this mod ceased. The last update is from 10th of October and https://gatherlite.labcake.org/ is down.
I might switch over to gathermate

**Comment by Motowatch** [comment]
I think I may be seeing the same bug with the latest version (1.3.3-Classic). 

I circle the Charred Vale mining and there are a few locations that despite being mined several times, do not seem to be recorded. 

On the Mini Map and Main Map there is no icon indicating ore had been found at those locations.

Fortunately the "Find Minerals" still finds them as I walk by...

.

**Comment by leoncard** [comment]
I was having the same issue, I have now replaced my methods.lua file for @drake2k's modified one and it is not missing nodes anymore https://github.com/Wuild/GatherLite/blob/210192de348c3ce5c578616c4f211b9a8dace45f/Scripts/methods.lua

**Comment by Wuild** [comment]
Sorry for the long delay. This issue should now be resolved in the version 2.0.0, if the error persist please contact me again.
