### ISSUE TITLE
Disable Quest Items

### ISSUE THREAD

**Issue by JumpY2k3** [Wuild/GatherLite#12]
Lot of quest items are displayed on the map as a treasure cause these are items which you need to open on the ground like a chest. 

Maybe add option "Hide/Show Quest-Items" on Minimap to disable them, or never track opening this things. Thanks a lot!

**Comment by Wuild** [comment]
it's hard since we're tracking the "open" spell wich is also used on quest items. im looking into this already.

**Comment by JumpY2k3** [comment]
Can you select with Itemname? You are displaying itemnames and items in the box on the main map, so I think you could check the name with common treasure names and only display them and otherwise skip them or add to "questitem"? 
I hope you understand what im talking about

**Comment by Wuild** [comment]
i'm afraid not, this would be broken for people playing the game in any other language then english

**Comment by Wuild** [comment]
what i maybe could do is if you enable debugging when picking a quest item "treasure" give me the current spell id it broadcasts via the debugging

**Comment by JumpY2k3** [comment]
How to enable debugging? I could do when I get a next quest with this.

**Comment by JumpY2k3** [comment]
Okay and what information you need? It shows:

Started gathering with Öffnen
Adding note ate XY
sharing node with guild
updating mini map nodes
updating world map nodes

**Comment by Wuild** [comment]
shit it not showing the spell ID h/o ill add it to the debug in the next patch

**Comment by Wuild** [comment]
please download version 1.0.32-classic and send me the same information you just did.

**Comment by JumpY2k3** [comment]
Hmm, I am in a dungeon and looting serpentbloom, no spell ID for this shown. Debugging says only  "Started gathering with Öffnen" nothing more.

**Comment by Wuild** [comment]
yeah looting in dungeons dont work

**Comment by JumpY2k3** [comment]
Ah damn, okay. Then I need to wait until I'm out.

**Comment by Wuild** [comment]
yeah classic doesnt have mapIDs for dungeons so we cannot add nodes to them.

**Comment by JumpY2k3** [comment]
No problem, if the other issues are fixed it will be a nice addon :))

**Comment by Wuild** [comment]
i'm working on it :)

**Comment by JumpY2k3** [comment]
If you need more information I could help you, may with coding or fixing, too. 
Maybe contact at discord or sth else, if you need msg me.

I will report IDs later after dungeon.

**Comment by JumpY2k3** [comment]
I'm now out of dungeon. It doesn't show IDs when I loot a herb. May the new version does not show debug correctly?

**Comment by Wuild** [comment]
add me on discord Wuild#5854 if you would like to help

**Comment by Wuild** [comment]
this has been fixed!
