### ISSUE TITLE
Incomplete corpus of nodes getting shipped with addon

### ISSUE THREAD

**Issue by tomalexander** [Wuild/GatherLite#122]
I noticed in the repo there is a `classic.lua` file under the `db` folder which contains someone's very incomplete corpus of gathering nodes. Is this intentional? It looks like something someone accidentally committed.  People with sharing disabled will certainly be surprised by some stranger's nodes appearing on their map when they update.

**Comment by Wuild** [comment]
This was intentional but has been removed, it was a predefined database that users uploaded. These where not synced by the addon.
