### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by nzcool** [Wuild/GatherLite#123]
1，能否将地图和小地图上的富瑟银矿和瑟银矿的图标区分开来？同一地点刷新两种矿石能否优先显示高级矿石的图标，这样采集路线会更加清晰。英雄之血的图标能否改成道具的图标加以分辨。
2，能否增加各类矿脉的显示与隐藏在地图上，比如，我只想看富瑟银矿的刷新地点，其他矿脉的图标隐藏。

**Comment by Wuild** [comment]
English please...
