### ISSUE TITLE
Spam of system messages when Gathering

### ISSUE THREAD

**Issue by bensussman** [Wuild/GatherLite#126]
**Describe the bug**
When I gather (ex: mine some ore) I see a huge spam of system messages in chat.

**To Reproduce**
1. Have System Messages on in chat (default general chat has them)
2. Mine some Ore on your character
3. Look at the chat and see a ton of `<GatherLite> 1446 1434` spam

**Expected behavior**
I expect NO chat messages from Gatherlite at all!

**Screenshots**
![WoWScrnShot_122719_004137](https://user-images.githubusercontent.com/86856/71503188-3461d200-2842-11ea-9aba-8a5860fc1a36.jpg)

**Additional context**
This is new with the update. Also seeing lots of "Friend was added" system message spam. Not sure if caused by GatherLite though.

**Comment by Wuild** [comment]
My bad, forgot a debugging message. it's fixed now
