### ISSUE TITLE
Nodes not showing - now in external addon?

### ISSUE THREAD

**Issue by linxus1981** [Wuild/GatherLite#128]
Has the database been ported into an external addon, or is that still a WIP?  Clicking the "use predefined database" on or off doesnt seem to do anything to make the large map of pre-exisitng node info show up.

**Comment by MarkusTeufelberger** [comment]
Also https://gatherlite.labcake.org/ seems down...

**Comment by Wuild** [comment]
This has been fixed in 3.0.0-alpha. Available for download now.
