### ISSUE TITLE
gatherlite.labcake.org not working

### ISSUE THREAD

**Issue by gitterrost4** [Wuild/GatherLite#131]
I am not sure if this belongs on this issue tracker or not. When logging into WoW, I get the message to "Please consider sharing your database over at our website http://gatherlite.labcake.org [...]". This Website gives me a CloudFlare page with a 522 (Connection Timed Out) error. Is this just temporary or should the login message be removed?

**Comment by Wuild** [comment]
Website is no longer in use!

**Comment by MarkusTeufelberger** [comment]
What's the data source for https://github.com/Wuild/GatherLite/tree/master/data then?
