### ISSUE TITLE
Sync is not working

### ISSUE THREAD

**Issue by valkum** [Wuild/GatherLite#132]
`GatherLite.tablelength(GatherLite.db.global.nodes)` in line 898 in `GatherLite:p2pDatabase` is 0 for my database.

It seems `GatherLite.db.global.nodes` is nil when passed to `tablelength`

I tried to replace `GatherLite.db.global.nodes` with `_GatherLite.nodes` but that did not work either.

**To Reproduce**
1. Go to 'Settings'
2. Click on Guild Sync 0 / x.'
4. Nothing happens

**Expected behavior**
Nodes should be synced with guild

**Comment by basic-settings** [comment]
I've cleared it up so it auto syncs with the guild when I log-in:

`if IsInGuild() and GatherLite.syncedNodes.guild == 0 then`

**Comment by Wuild** [comment]
This has been fixed in 3.0.0-alpha. Available for download now.
