### ISSUE TITLE
2.0.1 shows only nodes that I have discovered

### ISSUE THREAD

**Issue by ruthlesreb** [Wuild/GatherLite#133]
**Describe the bug**
When I view the map or minimap, the only nodes showing are ones that my toons have found in the first place. When I put in the previous version of gatherlite, all the old ones fro other users pop in. Does 2.0.1 have a combined database of all users?
I don't code so please read my words with that in mind. I may use the wrong terminology.

1. Go to any map
2. Click on any nodes
3. Only ones that my toons discovered are showing.

I was reading about donating some file here for you to combine them all. That's the reason I came here originally, but just realized in game this new problem.

**Comment by d3aths** [comment]
same. doesn't come with a database of nodes. i see in changelog the owner said the database would come in separate addon, but where can we find that?

**Comment by Wuild** [comment]
This has been fixed in 3.0.0-alpha. Available for download now.
