### ISSUE TITLE
Nodes showing impossible herbs

### ISSUE THREAD

**Issue by Alchmst1259** [Wuild/GatherLite#134]
**Describe the bug**
Node records seem to be getting recorded onto the wrong nodes.  This results is herbs (in my experience) showing up in impossible places, stacked on pre-existing possible nodes.  For instance, while walking through Durotar I can see numerous nodes that show as Plaguebloom, Mountain Silversage, or other high level herbs that don't spawn in Durotar.  If I mouse over them it will show collection history along the lines of "Plaguebloom x4, Earthroot x3," which to me suggests they are stacking collection records from a node in another zone on top of the collection records in Durotar (IE I collect Plaguebloom in Felwood but the collection data writes to an Earthroot note in Durotar).

**To Reproduce**
1. Collect herbs for months
2. Look at your map
3. See the wrong herbs
4. See this happening with increased frequency

**Expected behavior**
Think this is pretty self explanatory

**Screenshots**

![image](https://user-images.githubusercontent.com/63252965/78582480-8ecfde80-77f2-11ea-840e-5a9b48e8788a.png)

![image](https://user-images.githubusercontent.com/63252965/78582654-dce4e200-77f2-11ea-8444-ca40073ad39f.png)

**Additional context**
Don't know what else to say

**Comment by Wuild** [comment]
This has been fixed in 3.0.0-alpha. Available for download now.
