### ISSUE TITLE
New release = terrible frame loss

### ISSUE THREAD

**Issue by ATypeBlameaux** [Wuild/GatherLite#135]
Had very laggy/low frame game experience with new release gatherlite this morning.  Disabled it and things returned to normal.

**Comment by basic-settings** [comment]
I have the same behavior and same results.

**Comment by ATypeBlameaux** [comment]
Just updated to this morning's patch and continue to have same issue

**Comment by Wuild** [comment]
please try 3.0.3-alpha it may have been fixed
