### ISSUE TITLE
How does node sharing work?

### ISSUE THREAD

**Issue by gerbenvandijk** [Wuild/GatherLite#14]
Hi there, 

First of all, awesome stuff - thx.

A couple of questions regarding node sharing:

- Is node sharing enabled by default?
- Does it only work with players in a group or does it work with any player in the world who also has node sharing enabled?

Thanks a lot for taking the time!

**Comment by Wuild** [comment]
node sharing is not enabled by default, you have to enable it in the interface options.
It only works with guild and party members, blizzard has restricted how we can send these messages.

**Comment by Aergernis** [comment]
Does it "only" share the node collected this moment or does it share nodes on random basis every lets say 1 minute? If not, that would be nice to have.

**Comment by Wuild** [comment]
At the moment it only shares the node at the time they are collected.
I may how ever make some sort of full database share some time in the future.

**Comment by Wuild** [comment]
Or just some sort of predefined database with nodes from players who has shared there database to me :)

**Comment by gerbenvandijk** [comment]
Thanks a lot for the info!
