### ISSUE TITLE
Error when trying to access settings (/gather) or turn OFF debugging mode (/gather debugging)

### ISSUE THREAD

**Issue by Just-in-Milk** [Wuild/GatherLite#141]
**After installing the latest version from curseforge, addon loaded up nicely, icons are present on map/minimap, but I can't access the settings.** 

Date: 2020-04-12 14:56:15
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\GatherLite\scripts/main.lua line 33:
   attempt to call method 'ShowSettings' (a nil value)
Debug:
   GatherLite\scripts/main.lua:33: ?()
   ...ddOns\Details\Libs\AceConsole-3.0\AceConsole-3.0.lua:94: ?()
   ..\FrameXML\ChatFrame.lua:4690: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4351: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4387: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 tablelength = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:53
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 UnregisterComm = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 debug = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:39
 Printf = <function> defined @Interface\AddOns\Details\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 GatherSlash = <function> defined @Interface\AddOns\GatherLite\scripts/main.lua:30
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ScheduleTimer = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 findExistingLocalNode = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:150
 RegisterMessage = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 UpdateNode = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:185
 translate = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:45
 db = <table> {
 }
 UnregisterAllComm = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 NewVersionExists = false
 RegisterEvent = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 IterateModules = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 findNodeType = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:122
 RegisterNode = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:159
 Enable = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 print = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:34
 LoadMinimap = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:544
 GetModule = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceTimer-3.0\AceTimer-3.0.lua:172
 Deserialize = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 UnregisterChatCommand = <function> defined @Interface\AddOns\Details\Libs\AceConsole-3.0\AceConsole-3.0.lua:111
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceTimer-3.0\AceTimer-3.0.lua:160
 createMinimapNode = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:368
 GetName = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.l
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.7
  AtlasLootClassicData, vv1.4.7
  AtlasLootClassicDungeonsAndRaids, vv1.4.7
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BattlegroundTargets, v11304-1
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicAuraDurations, v
  ClassicCastbars, vv1.2.0-hotfix
  ClassicCastbarsOptions, v
  DBMCore, v1.13.42
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DruidBarClassic, v0.7.7
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  EZJunk, v1.0.1
  GatherLite, v3.0.7-alpha
  HealBot, v1.13.3.8
  HealBotData, v1.13.3.8
  HealBoten, v1.13.3.8
  HealBotOptions, v1.13.3.8
  HealBotTips, v1.13.3.8
  honorspy, v1.7.3
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LetMeCast, v1.3
  MaekorOverpowerAlert, v0.1
  ModernTargetFrame, v1.3.1
  OmniCC, v8.2.5
  Questie, v5.8.0 0 d9d2117b
  RareAware, v1.0
  RCLootCouncilClassic, v0.8.0
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.0.15
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TrinketMenu, v7.3.2
  WeakAuras, v2.16.6
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=605)

**I successfuly turned ON debugging just to try and see what will happen, and it actually did. After poking around for some time I concluded that this info is no use for me to fix the issue, and tried to turn it off... except another error:**

Date: 2020-04-12 14:58:12
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\GatherLite\scripts/main.lua line 39:
   attempt to index global 'GGatherLite' (a nil value)
Debug:
   GatherLite\scripts/main.lua:39: ?()
   ...ddOns\Details\Libs\AceConsole-3.0\AceConsole-3.0.lua:94: ?()
   ..\FrameXML\ChatFrame.lua:4690: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4351: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4387: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 tablelength = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:53
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 UnregisterComm = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 debug = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:39
 Printf = <function> defined @Interface\AddOns\Details\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 GatherSlash = <function> defined @Interface\AddOns\GatherLite\scripts/main.lua:30
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ScheduleTimer = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 findExistingLocalNode = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:150
 RegisterMessage = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 UpdateNode = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:185
 translate = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:45
 db = <table> {
 }
 UnregisterAllComm = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 NewVersionExists = false
 RegisterEvent = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 IterateModules = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 findNodeType = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:122
 RegisterNode = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:159
 Enable = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 print = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:34
 LoadMinimap = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:544
 GetModule = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceTimer-3.0\AceTimer-3.0.lua:172
 Deserialize = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 UnregisterChatCommand = <function> defined @Interface\AddOns\Details\Libs\AceConsole-3.0\AceConsole-3.0.lua:111
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceTimer-3.0\AceTimer-3.0.lua:160
 createMinimapNode = <function> defined @Interface\AddOns\GatherLite\scripts/methods.lua:368
 GetName = <function> defined @Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\Libs\AceAddon-3.0\AceAddon-3.0.l
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.7
  AtlasLootClassicData, vv1.4.7
  AtlasLootClassicDungeonsAndRaids, vv1.4.7
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BattlegroundTargets, v11304-1
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicAuraDurations, v
  ClassicCastbars, vv1.2.0-hotfix
  ClassicCastbarsOptions, v
  DBMCore, v1.13.42
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DruidBarClassic, v0.7.7
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  EZJunk, v1.0.1
  GatherLite, v3.0.7-alpha
  HealBot, v1.13.3.8
  HealBotData, v1.13.3.8
  HealBoten, v1.13.3.8
  HealBotOptions, v1.13.3.8
  HealBotTips, v1.13.3.8
  honorspy, v1.7.3
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LetMeCast, v1.3
  MaekorOverpowerAlert, v0.1
  ModernTargetFrame, v1.3.1
  OmniCC, v8.2.5
  Questie, v5.8.0 0 d9d2117b
  RareAware, v1.0
  RCLootCouncilClassic, v0.8.0
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.0.15
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TrinketMenu, v7.3.2
  WeakAuras, v2.16.6
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=605)

**Comment by Wuild** [comment]
Thank you, this has been fixed in the next patch
