### ISSUE TITLE
Nodes not all showing up in Felwood

### ISSUE THREAD

**Issue by candacea123** [Wuild/GatherLite#142]
Since the latest update, mountain silversage and dreamfoil are not showing up in Felwood.

Screenshot below normally would have a mountain silversage and dreamfoil node shown. And full map shows there are none of those nodes at all in Felwood.

![WoWScrnShot_041220_070310](https://user-images.githubusercontent.com/63548169/79070593-c1168b80-7c8b-11ea-967b-4619f0bdc040.jpg)

![Capture](https://user-images.githubusercontent.com/63548169/79070617-e6a39500-7c8b-11ea-89c1-4af1467e04e9.JPG)

**Comment by Wuild** [comment]
Thank you, they have been added to the database and will be available on the next patch
