### ISSUE TITLE
Minimap tooltip wrong type

### ISSUE THREAD

**Issue by xIGBClutchIx** [Wuild/GatherLite#144]
When highlighting a mining node it saids Herbalism but I think with the correct level.

**Comment by Wuild** [comment]
please submit a screenshot.

**Comment by xIGBClutchIx** [comment]
Screenshot here - https://i.imgur.com/BEd4kov.png

**Comment by Wuild** [comment]
wierd... i'm unable to replicate this...

**Comment by xIGBClutchIx** [comment]
Strange I did disable all other plugins and still getting it. It only happens to nodes that are actually there, the dot ones.

**Comment by Wuild** [comment]
Cant replicate it, but i found the faulty code and has been fixed now. Will be available on the next patch
