### ISSUE TITLE
Floating minimap icon outside the minimap

### ISSUE THREAD

**Issue by LarsOlt** [Wuild/GatherLite#149]
When I tick the option "Mini map icons" in the settings of gatherlite, I have a single icon floating in my  UI. When I uncheck the option its gone, including the minimap icons.

![Unbenannt](https://user-images.githubusercontent.com/32353679/83658748-ead09c80-a5c2-11ea-9658-ffb4e6142a67.png)

**All Addons I use:**

![Screenshot_1](https://user-images.githubusercontent.com/32353679/83659274-9c6fcd80-a5c3-11ea-8557-242db0262b98.png)
![Screenshot_2](https://user-images.githubusercontent.com/32353679/83659268-9a0d7380-a5c3-11ea-88cf-65bb9364ab50.png)

**Comment by Wuild** [comment]
So you close it and not tell me if it's fixed?

**Comment by LarsOlt** [comment]
I was using an outdated version, sry
