### ISSUE TITLE
LUA Error when opening Chest

### ISSUE THREAD

**Issue by Aergernis** [Wuild/GatherLite#15]
Hi,
when opening a chest i get the following LUA error:

`1x GatherLite\methods.lua:143: attempt to perform arithmetic on local 'coin' (a nil value)
GatherLite\methods.lua:143: in function `foundNode'
GatherLite\events.lua:86: in function `OnLootOpened'
GatherLite\events.lua:140: in function <GatherLite\events.lua:130>

Locals:
x = 0.252887
y = 0.487170
mapID = 1420
loot = <table> {
}
coin = nil
count = 4
(for index) = 1
(for limit) = 4
(for step) = 1
i = 1
lIcon = 133789
lName = "30 Kupfer"
lQuantity = 0
lQuality = nil
locked = 0
isQuestItem = false
slotType = 2
lLink = nil
i = 1
j = 9
val = "30"
(*temporary) = 1
(*temporary) = 9
(*temporary) = "30"
(*temporary) = 1
(*temporary) = 1
(*temporary) = 9
(*temporary) = "30"
(*temporary) = "attempt to perform arithmetic on local 'coin' (a nil value)"
HBD = <table> {
 mapData = <table> {
 }
 GetAllMapIDs = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:312
 UpdateCurrentPosition = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:241
 callbacks = <table> {
 }
 GetPlayerZone = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:516
 transforms = <table> {
 }
 GetLocalizedMap = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:296
 eventFrame = <unnamed> {
 }
 GetPlayerZonePosition = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:524
 GetPlayerWorldPosition = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:504
 GetZoneDistance = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:448
 GetUnitWorldPosition = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:492
 GetWorldCoordinatesFromZone = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:324
 GetWorldDistance = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:434
 GetWorldCoordinatesFromAzerothWorldMap = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:339
 GetZoneSize = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:303
 worldMapData = <table> {
 }
 UnregisterCallback = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 GetZoneCoordinatesFromWorld = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:356
 RegisterCallback = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 TranslateZoneCoordinates = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:411
 GetWorldVector = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:469
 GetAzerothWorldMapCoordinatesFromWorld = <function> defined @ClassicCodex\lib\HereBeDragons\HereBeDragons-2.0.lua:375
}
GatherLite = <table> {
 spellIDs = <table> {
 }
 drawWorldmap = <function> defined @GatherLite\methods.lua:286
 findSpell = <function> defined @GatherLite\methods.lua:63
 updateMiniMapPosition = <function> defined @GatherLite\settings.lua:280
 tablelength = <function> defined @GatherLite\methods.lua:20
 createWorldmapNode = <function> defined @GatherLite\methods.lua:443
 debug = <function> defined @GatherLite\methods.lua:13
 tooltip = GatherLiteTooltip {
 }
 RegisterCallback = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 gatherSpellRanges = <table> {
 }
 nodes = <table> {
 }
 insertDatabaseNode = <function> defined @GatherLite\methods.lua:205
 hideTooltip = <function> defined @GatherLite\GatherLite.lua:64
 TimeSinceLastUpdate = 0.101000
 UpdateInterval = 1
 ParseSentData = <function> defined @GatherLite\methods.lua:509
 needMapUpdate = false
 IsNodeInRange = <function> defined @GatherLite\methods.lua:97
 callbacks = <table> {
 }
 removeWorldmapNodes = <function> defined @GatherLite\methods.lua:505
 frames = <table> {
 }
 minimap = GatherLite_M`

**Comment by Wuild** [comment]
Thank you, ill look into this.

**Comment by Aergernis** [comment]
it's with german client if it's helpfull

**Comment by Wuild** [comment]
this should be fixed now.
