### ISSUE TITLE
New Black Lotus spawns

### ISSUE THREAD

**Issue by Just-in-Milk** [Wuild/GatherLite#150]
For obvious reasons, preexisting database is lacking new Black Lotus spawns for WoW Classic.

At the moment of creating this issue, information may not be complete, but some resources already have updated maps, like https://classicguides.org/black-lotus-farming-guide/

**Comment by wislock1999** [comment]
Hereunder the GatherLite\Data\herbs.lua file patched with new lotus spots. Based on GatherMate2 locations.
Data might not be as well sorted as original file. No issue playing with it since a month however.

[herbs.zip](https://github.com/Wuild/GatherLite/files/4918870/herbs.zip)

**Comment by Wuild** [comment]
new release with an updated database
