### ISSUE TITLE
Dropped support for Un'Goro dirt piles

### ISSUE THREAD

**Issue by Stonechewer** [Wuild/GatherLite#153]
**Describe the bug**
No longer tracking Un'Goro Soil mounds. This was the reason I used gatherlite rather than other gathering 

**To Reproduce**
There no longer seems to be an option to track soil. With AG coming out next week, soil is going to be in high demand. I'm going to go back to the older version for now, but would love to see it reintroduced in the next version.

**Expected behavior**
Un'goro soil piles will show up on the mini map and the overview map.

**Screenshots**
n/a I'm pretty sure you got this.

**Additional context**

**Comment by Wuild** [comment]
I will have a look at this...

**Comment by Wuild** [comment]
Just released version 3.2.0 which adds containers to the tracker, so this should be fixed now.
