### ISSUE TITLE
attempt to compare nil with number

### ISSUE THREAD

**Issue by remyspaan** [Wuild/GatherLite#154]
I always get this message when I load a zone or /ReloadUI

Debugging details:

On ReloadUI / Loading Game / Loading continent

Message: Interface\AddOns\GatherLite\scripts/methods.lua:743: attempt to compare nil with number
Time: Sat Jul 25 19:10:59 2020
Count: 1
Stack: Interface\AddOns\GatherLite\scripts/methods.lua:743: attempt to compare nil with number
[string "=[C]"]: ?
[string "@Interface\AddOns\GatherLite\scripts/methods.lua"]:743: in function `cb'
[string "@Interface\AddOns\GatherLite\scripts/methods.lua"]:714: in function `forEach'
[string "@Interface\AddOns\GatherLite\scripts/methods.lua"]:734: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua"]:55: in function <...s\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: 

When loading the map (pressing M):

Message: Interface\AddOns\GatherLite\scripts/methods.lua:881: attempt to index global 'WorldMapContinentDropDown' (a nil value)
Time: Sat Jul 25 19:12:51 2020
Count: 1
Stack: Interface\AddOns\GatherLite\scripts/methods.lua:881: attempt to index global 'WorldMapContinentDropDown' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\GatherLite\scripts/methods.lua"]:881: in function <Interface\AddOns\GatherLite\scripts/methods.lua:876>

Locals: 

Maybe it has something to do with the combination with ElvUI?

**Comment by Wuild** [comment]
Should be fixed now
