### ISSUE TITLE
Nil distance in instances (v3.2.3)

### ISSUE THREAD

**Issue by Byron-Miles** [Wuild/GatherLite#155]
**Describe the bug**
Error when in instances caused by 'distance' being nil on line 128 of Tracker.lua

**To Reproduce**
1. Enable some form of tracking
2. Go into an instance

**Potential Fix**
`if distance == nil or distance >= GatherLite.db.char.minimap.range then`

**Comment by Wuild** [comment]
Fixed in 3.2.4
