### ISSUE TITLE
Icons from Recources on Screen while Map is Closed

### ISSUE THREAD

**Issue by Itroll91** [Wuild/GatherLite#16]
I marked the Icons with red circels. 

A other little Mistake in the "Master" version I found also. At Zip version you Named it "Gatherlight- Master". The Space in the Name results in WOW woud not load the Mod.

![WoWScrnShot_083119_091751](https://user-images.githubusercontent.com/54697160/64060662-7cdcec00-cbd0-11e9-90ed-9cec57b5ba26.jpg)

Ps: Sry for my bad endlish, its not my nativ language.

**Comment by Wuild** [comment]
make sure ur using the latest version.
When downloaded from github you need to rename the folder to just GatherLite and remove the -master part

**Comment by Itroll91** [comment]
That was what I did Yesterday morning. ^^ Did u upload a new version sinc yesterday?


Also i got an LUA error after activiting Herb skill.

Date: 2019-08-31 09:29:51
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\GatherLite\GatherLite.lua line 554:
   attempt to index local 'classColor' (a nil value)
Debug:
   GatherLite\GatherLite.lua:554:
      GatherLite\GatherLite.lua:526
Locals:
locClass = nil
engClass = nil
locRace = nil
engRace = nil
gender = nil
name = nil
classColor = nil
addLoot = true
(*temporary) = <function> defined =[C]:-1
(*temporary) = GatherLiteTooltip {
 0 = <userdata>
 updateTooltip = 0.200000
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 TopOverlay = <unnamed> {
 }
}
(*temporary) = "Found by:"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "08"
(*temporary) = "/"
(*temporary) = "2019"
(*temporary) = " - "
(*temporary) = "16"
(*temporary) = ":"
(*temporary) = "49"
(*temporary) = ":"
(*temporary) = "31"
(*temporary) = ""
(*temporary) = "attempt to index local 'classColor' (a nil value)"
f = <unnamed> {
 0 = <userdata>
 texture = <unnamed> {
 }
}
node = <table> {
 GUID = "Player-4455-01590A36"
 type = "herbalism"
 date = <table> {
 }
 name = "erdwurzel"
 position = <table> {
 }
 target = "erdwurzel"
 loot = <table> {
 }
 icon = "134187"
 spellID = 2366
}
GatherLite = <table> {
 spellIDs = <table> {
 }
 findSpell = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:273
 updateMiniMapPosition = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:421
 createWorldmapNode = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:436
 UpdateMapNodes = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:575
 debug = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:237
 handleSpell = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:907
 needMapUpdate = false
 UpdateMinimapNodes = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:624
 gatherSpellRanges = <table> {
 }
 nodes = <table> {
 }
 hideTooltip = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:303
 TimeSinceLastUpdate = 0.657000
 ParseSentData = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:790
 foundOreOrHerb = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:836
 IsNodeInRange = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:309
 minimapFrames = <table> {
 }
 frames = <table> {
 }
 minimap = GatherLite_MinimapButton {
 }
 findSpellType = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:261
 UpdateInterval = 1
 nodeUpdated = false
 createMinimapNode = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:504
 defaultConfigs = <table> {
 }
 showingTooltip = false
 name = "GatherLite"
 isRetail = false
 print = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:233
 classColours = <table> {
 }
 foundTreasureChest = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:878
 mainFrame = <unnamed> {
 }
 tracker = <table> {
 }
 addNode = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:318
 isClassic = true
 showTooltip = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:289
 CopyDefaults = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:408
 tooltip = GatherLiteTooltip {
 }
 minimapFrame = <unnamed> {
 }
 version = "@project-version@"
}

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.4
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  DBMCore, v1.13.2
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  Enchantrix, v8.2.6392 (SwimmingSeadragon)
  GatherLite, v@project-version@
  Informant, v8.2.6374 (SwimmingSeadragon)
  Prat30, v3.2.30
  Prat30Libraries, v
  QuestieDevmaster, v4.0.10 BETA
  Scrap, v13.18
  ScrapMerchant, v13.18
  ScrapSpotlight, v13.18
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11302-1.0.7
  VendorPrice, v1.1.3
  BlizRuntimeLib_deDE v1.13.2.11302 <none>
  (ck=418)

**Comment by Wuild** [comment]
wrong addon version, please download the latest one

**Comment by Itroll91** [comment]
Okay, thanks! :D

**Comment by Itroll91** [comment]
All fine again with new Version. Thank you again.
