### ISSUE TITLE
Message Spam in Battlegrounds

### ISSUE THREAD

**Issue by ixidion** [Wuild/GatherLite#160]
**Describe the bug**
There is a message spam in System-Chat, when entering a Battleground. This happens every 5 sec or so.

**To Reproduce**
1. Enter a BG
2. Watch Message Spam in System Chat to happen: "Not in Raid Group"-like messages

**Expected behavior**
No message at all.

**Screenshots**
N/A

**Additional context**
v3.2.4

**Comment by Paroyer** [comment]
It's due to something regarding version check, I just deleted every damn function I could find with "version" in it. At that point I doubt we get an update soon and it was sincerly pissing me off

**Comment by Wuild** [comment]
This should be fixed now!
