### ISSUE TITLE
New nodes won't show after leaving the area

### ISSUE THREAD

**Issue by Beast815** [Wuild/GatherLite#162]
**Describe the bug**
When not playing with the built-in database newly found nodes won't be displayed after relog or leaving the area.

**To Reproduce**
1. Find new node
2. leave area or relog

**Expected behavior**
Found nodes should be displayed

**Comment by Wuild** [comment]
there is a bug currently where it's not saving settings or data, i am currently looking into this.

**Comment by Wuild** [comment]
This has finaly been fixed!
