### ISSUE TITLE
Un'Goro Soil showing up as green squares instead of icons

### ISSUE THREAD

**Issue by rbpaiett** [Wuild/GatherLite#163]
**Describe the bug**
Un'Goro Soil shows green squares on the map

**To Reproduce**

Enable Gatherlite
Open map in Un'Goro

**Expected behavior**
Expect to see Un'Goro Soil icons.

**Screenshots**
<img width="862" alt="Gatherlite Un'Goro Soil" src="https://user-images.githubusercontent.com/1621701/94502766-bc05b400-01b9-11eb-8991-16a2eb829700.png">

**Comment by Silvertower** [comment]
This is caused by the text "Open\\\\" missing as a prefix for "Soil" on line 333 of nodes.lua.

This line:
        icon = _GatherLite.iconPath .. "Soil",

Should be:
        icon = _GatherLite.iconPath .. "Open\\\\Soil",

**Comment by rbpaiett** [comment]
It worked nicely, thanks a lot!
