### ISSUE TITLE
Error when hovering over Mithril Ore in inventory

### ISSUE THREAD

**Issue by ghost** [Wuild/GatherLite#165]
Message: Interface\AddOns\GatherSage2\Core.lua:559: bad argument #5 to 'format' (string expected, got nil)
Time: Sun Oct 11 01:13:19 2020
Count: 1
Stack: Interface\AddOns\GatherSage2\Core.lua:559: bad argument #5 to 'format' (string expected, got nil)
[C]: ?
[C]: in function `format'
Interface\AddOns\GatherSage2\Core.lua:559: in function `ProcessTooltip'
Interface\AddOns\GatherSage2\Core.lua:250: in function <Interface\AddOns\GatherSage2\Core.lua:239>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
...
[C]: ?
[C]: ?
[C]: ?
[C]: ?
...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:98: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96>
[C]: ?
[C]: ?
[C]: in function `SetBagItem'
Interface\FrameXML\ContainerFrame.lua:1327: in function <Interface\FrameXML\ContainerFrame.lua:1298>
Interface\AddOns\tdBag2\UI\Component\ItemBase.lua:164: in function <Interface\AddOns\tdBag2\UI\Component\ItemBase.lua:145>

Locals:

**Comment by Wuild** [comment]
This is not GatherSage2
