### ISSUE TITLE
No nodes loading in Add-on since the most recent update

### ISSUE THREAD

**Issue by kriminy** [Wuild/GatherLite#174]
Hey, I've tried clearing cache, disabling all add-ons but this one, but the add-on doesn't load any gathering nodes.

I enabled LUA errors, and got the following 2 error messages right as the game loaded:

#1
Message: ...Lite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua:70: script ran too long
Count: 1
Stack: ...Lite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua:70: script ran too long
[string "@Interface\AddOns\GatherLite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...Lite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\GatherLite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface\AddOns\GatherLite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua"]:623: in function <...Lite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: func = <function> defined @Interface\AddOns\GatherLite\scripts\main.lua:58
(*temporary) = false
(*temporary) = nil
(*temporary) = "script ran too long"
type = <function> defined =[C]:-1
xpcall = <function> defined =[C]:-1
errorhandler = <function> defined @Interface\AddOns\GatherLite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua:61

#2
Message: ...Lite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua:70: script ran too long
Count: 1
Stack: ...Lite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua:70: script ran too long
[string "@Interface\AddOns\GatherLite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...Lite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\GatherLite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface\AddOns\GatherLite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua"]:623: in function <...Lite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: func = <function> defined @Interface\AddOns\GatherLite\scripts\main.lua:58
(*temporary) = false
(*temporary) = nil
(*temporary) = "script ran too long"
type = <function> defined =[C]:-1
xpcall = <function> defined =[C]:-1
errorhandler = <function> defined @Interface\AddOns\GatherLite\scripts\libraries\AceAddon-3.0\AceAddon-3.0.lua:61

**Comment by kriminy** [comment]
I'm getting another LUA error after using a mining node. I wasn't sure if I should open another issue ticket with this or not.

Message: Interface\AddOns\GatherLite\scripts\methods.lua:264: attempt to perform arithmetic on field 'count' (a nil value)
Count: 4
Stack: Interface\AddOns\GatherLite\scripts\methods.lua:264: attempt to perform arithmetic on field 'count' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\GatherLite\scripts\methods.lua"]:264: in function `UpdateNode'
[string "@Interface\AddOns\GatherLite\scripts\methods.lua"]:289: in function `?'
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by Wuild** [comment]
i have made some changes... please try the latest version (5.1.1) and report back

**Comment by kriminy** [comment]
Everything seems to be working great. Thank you!
