### ISSUE TITLE
Support WowUP

### ISSUE THREAD

**Issue by lgrano** [Wuild/GatherLite#175]
Overwolf has blocked wowup from using the curseforge api, currently there's no way to get and update GatherLite via wowup.
When trying to install via github url, wowup says it require a zip release with a -bc or -bcc suffix for burning crusade.
Wowup also supports [Wowuphub](https://wowup.io/guide/wowup/hub), Wowinterface or Wago as alternative hosting platform, for most users would be easier to use those instead of github.

**Comment by Wuild** [comment]
GatherLite is available on wowinterface already.

**Comment by lgrano** [comment]
Thanks, ive installed from wowinterface, you have to pass the url manually to wowup for some reason, maybe a issue on wowup client.

**Comment by MarkusTeufelberger** [comment]
Wowinterface seems to only have version 6.0.0 available (https://www.wowinterface.com/downloads/author-352998.html), could you please check what's the issue there?

Edit: https://addons.wago.io/addons/gatherlite seems to have version 7.0.0 available, also not the latest one. Only https://www.curseforge.com/wow/addons/gatherlite has 7.1.0 available as of today.
