### ISSUE TITLE
Nodes not appearing on mini map at all on new character

### ISSUE THREAD

**Issue by ROFLBOB** [Wuild/GatherLite#176]
**Description**
All nodes (mining, herb, container, fish) suddenly stopped appearing on the mini-map on a new character. It was working when I first started the character, but suddenly stopped. I don't know what I was doing when it stopped working. GatherLite still works on my other characters. I've checked all settings and I can't get it working - I've reinstalled via Curse and manually (it says 5.1.1 in the app, but when i load in it says 5.1.0), disabled all other add-ons, adjusted the settings numerous times. I am using the predefined database. The nodes still appear on my Area Map, just not on my minimap. 

Mining is selected from the filter.  My minimap settings are as follows:
Keep nodes on minimap edge - checked
Show loot on node tooltip - checked
Show nodes closer than **784** units 
Icon Size: 12
Icon Opacity: .5
Hide nodes closer than **27** units

show nodes on the minimap - checked

I've adjusted these settings all around and they don't seem to have any effect. I attempted to find a solution by deleting multiple files in the WoW Classic directory but haven't had any luck. The files I deleted were GatherLite.lua, GatherLite.lua.bak, and my character folder in {account}/Ateish/Nomikai (my character name).

**Comment by ROFLBOB** [comment]
I discovered that the issue above only happens in azuremyst and bloodmyst island, the dranaei starting areas. I took my new character (a dranaei) to Auberdine and Menethil harbor, and the minimap icons have reappeared.

**Comment by Wuild** [comment]
This was due to an areaID error in the database... this has been fixed now, and will be available on the next update
