### ISSUE TITLE
Tooltip difficulty incorrect 

### ISSUE THREAD

**Issue by ketonic** [Wuild/GatherLite#181]
**Describe the bug**
When hovering over a herb or mining node the color shown for that difficulty is wrong. Cobalt went grey to soon, and as there are two frozen herbs they are shown Yellow when they should be red.

**To Reproduce**
1. Go to 'Dragonblight or Zul'Drak'
2. Hover on 'A frozen herb in both zones'

**Expected behavior**
Herbs and mining nodes showing the correct difficulty. 

**Additional context**
Also, the text it self is shown outside the tool tip box sometimes, think its down to some herbs with a short name.

**Comment by Wuild** [comment]
This has been fixed and will be correct on the next update
