### ISSUE TITLE
Sending messages to chat when in a dungeon finder?

### ISSUE THREAD

**Issue by Valacor87** [Wuild/GatherLite#186]
**Describe the bug**
Whenever I enter a dungeon through the dungeon finder, and have GatherLite enabled, i am constantly getting a message in chat that reads "You aren't in a party."  I went through all the options for the addon and can not find anything that mentions sending things to chat.   This only happens inside a dungeon finder group (instance group)  Its worth noting that I am using the addon in WoTLK Classic if that makes any difference.

**To Reproduce**
1. Enable GatherLite
2. Que for and enter a dungeon
3. Watch chat
4. Should receive the "You aren't in a party." message every 15-30 seconds

**Expected behavior**
See picture bellow

**Screenshots**
![image](https://github.com/Wuild/GatherLite/assets/137644556/07adc141-cf5c-4042-b56f-419a797c07f3)

**Additional context**
I was able to narrow down that it was GatherLite doing it by going through and disabling/enabling my addons one at a time until it stopped happening.

**Comment by Wuild** [comment]
I've done some changed to the p2p messaging, try out version 7.0.7 see if that fixes it!

**Comment by Valacor87** [comment]
Hmm thought I was updated fully, Curseforge didn't recognize 7.0.7 as being ready for update. I'll try it out and let you know if it keeps happening!

**Comment by Wuild** [comment]
i just published it, give it a couple of minutes and it should show up

**Comment by Valacor87** [comment]
Fix worked! You rock!

**Comment by Wuild** [comment]
Great! Thanks for reporting!
