### ISSUE TITLE
Need to handle coins in treasure chests

### ISSUE THREAD

**Issue by Reloque** [Wuild/GatherLite#2]
Right now you are assuming that every loot item in a treasure chest is an item, and any coins in the chest cause an error. Specifically, GetLootSlotLink() returns nil if the item is money, and you aren't handling that case.

**Comment by Wuild** [comment]
i will have a look at this when classic is available so i can find some treasure chests...

**Comment by Wuild** [comment]
i think i have fixed this, could you give it a try?
