### ISSUE TITLE
Tooltip not working

### ISSUE THREAD

**Issue by Aergernis** [Wuild/GatherLite#26]
the tooltip when hovering over nodes on map or minimap dosen't work correctly. it shows the node name within the tooltipframe, but the rest from last visited onward is not in the frame bur just plain text nearby the frame. it also shows lua error : 

`1x GatherLite\methods.lua:459: attempt to index local 'classColor' (a nil value)
GatherLite\methods.lua:459: in function <GatherLite\methods.lua:440>

Locals:
classColor = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = GatherLiteTooltip {
 0 = <userdata>
 updateTooltip = 0.200000
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 TopOverlay = <unnamed> {
 }
}
(*temporary) = "Found by:"
(*temporary) = "|cffffffff30/08/2019 - 07:34:29|r"
(*temporary) = <userdata>
(*temporary) = "/"
(*temporary) = "08"
(*temporary) = "/"
(*temporary) = "2019"
(*temporary) = " - "
(*temporary) = "07"
(*temporary) = ":"
(*temporary) = "34"
(*temporary) = ":"
(*temporary) = "29"
(*temporary) = "|r"
(*temporary) = "attempt to index local 'classColor' (a nil value)"
f = miningworldmap29 {
 0 = <userdata>
 texture = <unnamed> {
 }
}
GatherLite = <table> {
 spellIDs = <table> {
 }
 drawWorldmap = <function> defined @GatherLite\methods.lua:327
 findSpell = <function> defined @GatherLite\methods.lua:69
 updateMiniMapPosition = <function> defined @GatherLite\settings.lua:300
 tablelength = <function> defined @GatherLite\methods.lua:20
 createWorldmapNode = <function> defined @GatherLite\methods.lua:489
 debug = <function> defined @GatherLite\methods.lua:13
 tooltip = GatherLiteTooltip {
 }
 RegisterCallback = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 classColours = <table> {
 }
 gatherSpellRanges = <table> {
 }
 needMapUpdate = false
 nodes = <table> {
 }
 insertDatabaseNode = <function> defined @GatherLite\methods.lua:226
 hideTooltip = <function> defined @GatherLite\GatherLite.lua:64
 TimeSinceLastUpdate = 0.663000
 removeWorldmapNodes = <function> defined @GatherLite\methods.lua:538
 ParseSentData = <function> defined @GatherLite\methods.lua:547
 migrate = <function> defined @GatherLite\methods.lua:606
 IsNodeInRange = <function> defined @GatherLite\methods.lua:89
 callbacks = <table> {
 }
 checkNodePositions = <function> defined @GatherLite\methods.lua:522
 frames = <table> {
 }
 minimap = GatherLite_MinimapButton {
 }
 locale = <function> defined @GatherLite\methods.lua:49
 findSpellType = <function> defined @GatherLite\methods.lua:54
 createMinimapNode = <function> defined @GatherLite\methods.lua:504
 showTooltip = <function> defined @GatherLite\GatherLite.lua:50
 UpdateInterval = 1
 createFrame = <function> defined @GatherLite\methods.lua:471
 findExistingNode = <function> defined @GatherLite\methods.lua:99
 leadingZeros = <function> defined @GatherLite\methods.lua:430
 defaultConfigs = <table> {
 }
 showingTooltip = false
 version = "@project-version@"
 updateDatabaseNode = <function> defined @GatherLite\methods.lua:288
 foundNode = <function> defined @GatherLite\methods.lua:121
 WorldMapOpen = true
 isClassic = true
 mainFrame = <unnamed> {
 }
 tracker = <table> {
 }
 createNodeTooltip = <function> defined @GatherLite\methods.lua:439
 print = <function> defined @GatherLite\methods.lua:8
 minimapFrame = <unnamed> {
 }
 CopyDefaults = <function> defined @GatherLite\methods.lua:31
 UnregisterCallback = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 drawMinimap = <function> defined @GatherLite\methods.lua:378
 name = "GatherLite"
}
node = <table> {
 GUID = "Player-4440-00B137A1"
 type = "mining"
 date = <table> {
 }
 player = <table> {
 }
 name = "Zinnvorkommen"
 position = <table> {
 }
 target = "zinnvorkommen"
 loot = <table> {
 }
 icon = 135235
 spellID = 2576
}
lootTable = false
`

**Comment by pquerner** [comment]
Tooltip looks different now from old and new data.

https://i.imgur.com/97dhGde.png
https://i.imgur.com/X9rX2qs.png

**Comment by Wuild** [comment]
wierd, could you do a /reload and see if the errors persists?

**Comment by Ecilam** [comment]
French user and GatherLite v1.1.4.

Same error.

**Comment by pquerner** [comment]
Yes, still a thing after /reload. Only for old nodes the tooltip is broken (gathered with old version installed).

**Comment by Aergernis** [comment]
as a quick fix i edited the gatherlite.lua in savedvariables for every node so that the player array has now class, race, name and realm not only realm.

**Comment by Wuild** [comment]
it should have added it to all of them during the migration...

**Comment by Aergernis** [comment]
didn't seem to happen

**Comment by pquerner** [comment]
Can we trigger the migration again per CLI perhaps?

**Comment by Wuild** [comment]
i think ive fixed it. uploading new release soon.

**Comment by pquerner** [comment]
It fixes it now once you hover over the node the first time.
