### ISSUE TITLE
Allow option to reduce opacity of icons on minimap

### ISSUE THREAD

**Issue by misc213** [Wuild/GatherLite#28]
The add-on works great, thank you for your work.

I have one annoyance and that is the icons display over top and hide the Find Minerals icons.  It's great to know where previous nodes are but Find Minerals should have priority.

Can the icons draw underneath Find Minerals or can you add an option to set opacity on gatherlite minimap icons?

**Comment by Wuild** [comment]
what version are you using?
in version 1.1.4 the node icons will be hidden when closer than 70 yards from it.

**Comment by misc213** [comment]
Thanks, yeah I was on an older version. Looks good
