### ISSUE TITLE
Sync database

### ISSUE THREAD

**Issue by pquerner** [Wuild/GatherLite#29]
Its cool that you sync your node database with newely found nodes, but it could also help to periodically send out "old" found nodes you don't farm anylonger to your party/guild in order to build a larger database.

**Comment by MarkusTeufelberger** [comment]
At least having an option to dump your whole database out to your party/guild on demand would be nice.

**Comment by netlore** [comment]
Perhaps when anyone gathers a node it could post out 2 other nodes and work its way around the list collected by that person in a loop... so that eventually all their nodes would find the way to new people, without overloading the backchannel.

**Comment by Wuild** [comment]
i'm currently working on a system for this

**Comment by Wuild** [comment]
Here is an experimental function in guild p2p sharing https://github.com/Wuild/GatherLite/commit/d89fd749c13ebda3ca6363b14c092a58ec77d1d2

**Comment by MarkusTeufelberger** [comment]
I looked a bit deeper into it and would like to suggest using https://repos.wowace.com/wow/ace3/trunk/AceComm-3.0/ChatThrottleLib.lua to send the full database on a ticker every 15 minutes or so to the guild/raid/both. Currently the code seems to load the whole database, randomly select 5 nodes and send them, every 2 seconds. This is inefficient and it will take a very(!) long time until all nodes are shared (kinda the inverse of the birthday paradox).

**Comment by MarkusTeufelberger** [comment]
There could also be a function to dump/send/sync your database on demand to a player via the "WHISPER" AddonMessage functionality.

I'm actually more and more leaning towards making this functionality mostly manual (maybe start an automatic dump once per game session upon login) instead of having this constantly run in the background.

**Comment by Wuild** [comment]
Experimental is now on github where we send the whole database instead of just random nodes

**Comment by pquerner** [comment]
Since the latest changes I think I am loosing nodes. I am 100% certain gathered some herbs in tirisfall and silverpine forest - the nodes are now gone. Is there some "maximum" nodes ?

**Comment by Wuild** [comment]
no but the latest version does, remove faulty nodes wich couldnt be fixed.
