### ISSUE TITLE
Debug mode on

### ISSUE THREAD

**Issue by Zsolowin** [Wuild/GatherLite#3]
Debug logging is set to on and the addon produces a lot of chatter in the chat window when accessing a node.

**Comment by Wuild** [comment]
this is fixed

**Comment by Zsolowin** [comment]
Awesome thanks

**Comment by Wuild** [comment]
it will be off by default now but if you'r still having issues do /gather debugging off

**Comment by Zsolowin** [comment]
cool I couldn't find a list of commands anywhere I figured there was a setting for it. You should add the /gather commands to the readme and the addon page for twitch

**Comment by Wuild** [comment]
i should.... busy playing classic though ;)

**Comment by Zsolowin** [comment]
haha fair enough thanks for the addon and the quick response happy leveling

**Comment by Wuild** [comment]
thx, you to :)
