### ISSUE TITLE
Grab database from sites like wowhead

### ISSUE THREAD

**Issue by pquerner** [Wuild/GatherLite#30]
Wowhead and other sites have a huge database of node spawning. This addon could use this information, optionally, don't you think?
Problem probably is how do we get that data and in which form must we feed it to the addon?

**Comment by AskAlice** [comment]
pls daddy

**Comment by AskAlice** [comment]
+1

**Comment by JulianMoreno2** [comment]
+1

**Comment by Wuild** [comment]
Wowhead does not currently supply an API or XML feed on the node locations, i'm working on somthing else though

**Comment by pquerner** [comment]
@Wuild  

https://www.gamermaps.net/map/world-of-warcraft/classic#5.64.-308.1
