### ISSUE TITLE
Green Squares on Tooltips/Maps

### ISSUE THREAD

**Issue by ghost** [Wuild/GatherLite#31]
Please see attached. I upgraded from an older version, but I always delete folder and extract new folders.

Files under WTF were not touched. Disabled all other addons to test as well.

https://www.archaicbinary.net/stuff/minimap-tooltip.PNG
https://www.archaicbinary.net/stuff/map-icons.PNG

**Comment by Wuild** [comment]
ur not using the latest version

**Comment by ghost** [comment]
So I just updated again, and the tool tip is fixed, there are no icons on the new one. The version string is not filled but that's fine.

The world map does indeed still have green squares.

**Comment by ghost** [comment]
Okay apparently things are working fine, the old data from 1.0.9-classic is bad. I will have to manually fix the old DB files.

**Comment by Wuild** [comment]
wierd...

**Comment by Wuild** [comment]
If you where using an older version i do apologize, i did change how we select icons on the nodes, this is probably the issue here, on the latest version is should change the icon to the new one if found again
