### ISSUE TITLE
Hide the minimap icon entirely?

### ISSUE THREAD

**Issue by goldenpipes** [Wuild/GatherLite#32]
IS there a way to hide the minimap icon?  Not the NODES themselves.

Also, alternatively have the minimap button LDB support for bazooka/titanpanel?

CHEERS!

**Comment by Wuild** [comment]
Download the latest version and you’ll have the option to hide the icon in the interface settings. 

I don’t know if I’m gonna add support for titanpanel and what ever. If anyone is willing todo this they can do it :)
