### ISSUE TITLE
Marks not saving on higher skill nodes

### ISSUE THREAD

**Issue by lvangh** [Wuild/GatherLite#33]
Hello, 

I know this is a new experimental version, and I'm very familiar with the gatherer version from 1.12. When you attempt to gather a node that is higher than your skill the node should still appear on the map even though you can't get it. This is to mark the spots to go to later. 

Currently this version is not marking higher skill nodes. Maybe this is a limitation from the newer API. 

Thank you for making this BTW - I was getting desperate only a week into release! :P

**Comment by Wuild** [comment]
This is not possible currently to my knowledge, i may look into this at a later point though

**Comment by lvangh** [comment]
I've done a little Lua stuff here and there for 1.12. I think one option is to register the constant and then read the UI text "Requires Mining" string. I may be able to dig up some old code if you need an example. 

The constant might be "UNIT_SKINNABLE_ROCK" but I'm not sure that should convert to "Requires Mining"

But roughly it was something like 
  if event == "UNIT_SKINNABLE_ROCK" then
		(your code here to mark the node on the map)
    end

**Comment by Wuild** [comment]
your welcome to create a pull request if you like
im tyring to have the addon available on all languages and reading the text would make impossible unless i find people to translate it.

**Comment by lvangh** [comment]
ok, maybe i can play around with it later! ty :p
