### ISSUE TITLE
LUA error spam

### ISSUE THREAD

**Issue by MADSOFTWARE** [Wuild/GatherLite#34]
Message: Interface\AddOns\GatherLite\methods.lua:536: HereBeDragons-Pins-2.0: AddMinimapIconWorld: 'instanceID', 'x' and 'y' must be numbers
Time: Mon Sep  2 15:04:35 2019
Count: 1448
Stack: Interface\AddOns\GatherLite\methods.lua:536: HereBeDragons-Pins-2.0: AddMinimapIconWorld: 'instanceID', 'x' and 'y' must be numbers
[C]: in function `error'
...erLite\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:540: in function `AddMinimapIconWorld'
Interface\AddOns\GatherLite\methods.lua:536: in function `createMinimapNode'
Interface\AddOns\GatherLite\methods.lua:398: in function `drawMinimap'
Interface\AddOns\GatherLite\events.lua:18: in function <Interface\AddOns\GatherLite\events.lua:14>

Locals: (*temporary) = "HereBeDragons-Pins-2.0: AddMinimapIconWorld: 'instanceID', 'x' and 'y' must be numbers"

**Comment by Wuild** [comment]
looks like you have some sort of error in your database

**Comment by MADSOFTWARE** [comment]
This is a fresh install of the addon. Or is it saving a database somewhere else on the computer?

**Comment by Wuild** [comment]
what version of game and addon are you using?

**Comment by Wuild** [comment]
this should now be fixed

**Comment by MADSOFTWARE** [comment]
Hi!

Great. the error-spam has subsided!

It is throwing this error every time a node is mined however, and it is not adding any node to the map.

Version: WoW Classic
This is using the latest GathererLite /release.


________________________________________________________________________________________________
Message: Interface\AddOns\GatherLite\methods.lua:90: attempt to perform arithmetic on local 'nodePosX' (a nil value)
Time: Wed Sep  4 14:25:18 2019
Count: 3
Stack: Interface\AddOns\GatherLite\methods.lua:90: attempt to perform arithmetic on local 'nodePosX' (a nil value)
Interface\AddOns\GatherLite\methods.lua:90: in function `IsNodeInRange'
Interface\AddOns\GatherLite\methods.lua:110: in function `findExistingNode'
Interface\AddOns\GatherLite\methods.lua:172: in function `foundNode'
Interface\AddOns\GatherLite\events.lua:67: in function <Interface\AddOns\GatherLite\events.lua:31>

Locals: myPosX = 0.462405
myPosY = 0.304024
nodePosX = nil
nodePosY = nil
spellType = "mining"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'nodePosX' (a nil value)"
GatherLite = <table> {
 spellIDs = <table> {
 }
 drawWorldmap = <function> defined @Interface\AddOns\GatherLite\methods.lua:334
 findSpell = <function> defined @Interface\AddOns\GatherLite\methods.lua:69
 updateMiniMapPosition = <function> defined @Interface\AddOns\GatherLite\settings.lua:300
 tablelength = <function> defined @Interface\AddOns\GatherLite\methods.lua:20
 createWorldmapNode = <function> defined @Interface\AddOns\GatherLite\methods.lua:508
 debug = <function> defined @Interface\AddOns\GatherLite\methods.lua:13
 tooltip = GatherLiteTooltip {
 }
 RegisterCallback = <function> defined @Interface\AddOns\GatherLite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 classColours = <table> {
 }
 needMapUpdate = false
 gatherSpellRanges = <table> {
 }
 removeWorldmapNodes = <function> defined @Interface\AddOns\GatherLite\methods.lua:565
 nodes = <table> {
 }
 insertDatabaseNode = <function> defined @Interface\AddOns\GatherLite\methods.lua:233
 hideTooltip = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:64
 TimeSinceLastUpdate = 0.626000
 UpdateInterval = 1
 ParseSentData = <function> defined @Interface\AddOns\GatherLite\methods.lua:574
 migrate = <function> defined @Interface\AddOns\GatherLite\methods.lua:649
 IsNodeInRange = <function> defined @Interface\AddOns\GatherLite\methods.lua:89
 callbacks = <table> {
 }
 checkNodePositions = <function> defined @Interface\AddOns\GatherLite\methods.lua:549
 frames = <table> {
 }
 minimap = GatherLite_MinimapButton {
 }
 locale = <function> defined @Interface\AddOns\GatherLite\methods.lua:49
 findSpellType = <function> defined @Interface\AddOns\GatherLite\methods.lua:54
 createMinimapNode = <function> defined @Interface\AddOns\GatherLite\methods.lua:527
 showTooltip = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:50
 findDuplicateNode = <function> defined @Interface\AddOns\GatherLite\methods.lua:628
 createFrame = <function> defined @Interface\AddOns\GatherLite\methods.lua:490
 findExistingNode = <function> defined @Interface\AddOns\GatherLite\methods.lua:99
 leadingZeros = <function> defined @Interface\AddOns\GatherLite\methods.lua:437
 defaultConfigs = <table> {
 }
 showingTooltip = false
 version = "@project-version@"
 updateDatabaseNode = <function> defined @Interface\AddOns\GatherLite\methods.lua:295
 foundNode = <function> defined @Interface\AddOns\GatherLite\methods.lua:121
 WorldMapOpen = false
 isClassic = true
 mainFrame = <unnamed> {
 }
 tracker = <table> {
 }
 createNodeTooltip = <function> defined @Interface\AddOns\GatherLite\methods.lua:446
 print = <function> defined @Interface\AddOns\GatherLite\methods.lua:8
 minimapFrame = <unnamed> {
 }
 CopyDefaults = <function> defined @Interface\AddOns\GatherLite\methods.lua:31
 UnregisterCallback = <function> defined @Interface\AddOns\GatherLite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 drawMinimap = <function> defined @Interface\AddOns\GatherLite\methods.lua:385
 name = "GatherLite"
}
