### ISSUE TITLE
Icon on main screen and won't go away

### ISSUE THREAD

**Issue by WoWBready** [Wuild/GatherLite#35]
https://imgur.com/a/s39hWIq

**Comment by adonna55** [comment]
have the same issue and I am running the most current version GatherLite-1.0.18. Funny thing is, I never open my map in full screen so I have no idea how they are 'stuck' there. Logging on and off, different characters, disabling addon/reloading/re-enabling addon/reloading, still stays! 

Other current addons:
Bagnon
Bigwigs
BeQuiet
Canimogit?
Championcommander
Dominos
Easymount
Littlewigs
Fishing Buddy
Mik's Scrolling Battle Text
Garrison Mission manager
Threat Plates
TomTom
tuliarange
vuhdo
world quest list
omnicc
orderhallcommander
sexymap
slidebar

![WoWScrnShot_090219_210353_LI](https://user-images.githubusercontent.com/43224494/64139168-92673700-cdc5-11e9-851b-bc0b974685fb.jpg)

Edit: Added pic to show you can hover over these floating icons and they give gather info: 
![WoWScrnShot_090219_211558_LI](https://user-images.githubusercontent.com/43224494/64139638-31d8f980-cdc7-11e9-853d-7dc97d78ab5a.jpg)

Thank you!

**Comment by oliverloenberg** [comment]
I sadly have the exact same problem. 

I've got other addons installed such as:

Auctionator
ClassicAuraDurations
ClassicSpellActivations
Details! Damage Meter
Vendor Price
EZ Junk

Hope to have issue resolved soon! It's a real pain to look at in the long run.

Thanks.

**Comment by Wuild** [comment]
make sure ur using the latest version
1.1.5-retail or 1.1.5-classic and report back

**Comment by adonna55** [comment]
where can I get it it then as I literally dl it yesterday from curse. Is it
posted on another site? Thanks
