### ISSUE TITLE
Unexpected unstoppable LUA-Errors since last Night.

### ISSUE THREAD

**Issue by Comp4ny** [Wuild/GatherLite#36]
Never Problems since i use GatherLITE.
Last Night my first run on HdW and my FPS are dropping from over 200 to under 30 step by step. No new Addons installed, the newest update is installed... re-install from the Addons folder to.. but i have now unstoppable LUA-Errors from GatherLITE. I cant use it anymore.

I deactivated all my Addons, only GatherLITE is active... no results. Only GatherLITE give me LUA-Errors.

`Message: ...erLite\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:714: HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers
Time: Tue Sep  3 11:44:17 2019
Count: 11423
Stack: ...erLite\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:714: HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers
[C]: in function `error'
...erLite\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:714: in function `AddWorldMapIconMap'
Interface\AddOns\GatherLite\methods.lua:518: in function `createWorldmapNode'
Interface\AddOns\GatherLite\methods.lua:362: in function `drawWorldmap'
Interface\AddOns\GatherLite\events.lua:19: in function <Interface\AddOns\GatherLite\events.lua:14>

Locals: (*temporary) = "HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers"
`

**Comment by Wuild** [comment]
This should now be fixed in 1.1.7
