### ISSUE TITLE
World drops shouldn't be recorded

### ISSUE THREAD

**Issue by MarkusTeufelberger** [Wuild/GatherLite#37]
NPCs like this one in Ashenvale spawn a chest upon death that gets tracked + recorded by this addon:
https://classic.wowhead.com/npc=3928/rotting-slime

The chest is this one:
https://classic.wowhead.com/object=19021/rusty-chest

Since they are not spawning in fixed locations, only a certain area (and only spawn on the spot the NPC dies), the location of these chests should not be recorded by this addon.

**Comment by Wuild** [comment]
There is no way to determine if the "chest" in this case would be a world drop or not.

**Comment by MarkusTeufelberger** [comment]
I wonder how websites like Wowhead track the location of these nodes?

**Comment by Wuild** [comment]
my guess is that they dont track anything but rather add them manually.

**Comment by MarkusTeufelberger** [comment]
GatherLite at least definitely does know the name of the container, right? Could there be a blacklist of container names that are not being recorded or dropped from the database at least?

**Comment by Wuild** [comment]
in that case i would need a database of all the "chests" wich it shouldnt record on all languages.

**Comment by MarkusTeufelberger** [comment]
I also got the harvest festival items as "treasure" node in my database now. I'd be more than willing to help with creating such an ignore/purge list. In general I think wowhead already has a lot of this data, so just knowing the english name should already be enough to compile this list:

https://fr.classic.wowhead.com/object=19021/coffre-rouill%C3%A9
https://de.classic.wowhead.com/object=19021/rostige-truhe
https://es.classic.wowhead.com/object=19021/cofre-oxidado
etc. (e.g. try ru.classic.wowhead.com with the same object id)
