### ISSUE TITLE
Clicking on a resource node without having the profession doesn't record the node location

### ISSUE THREAD

**Issue by MarkusTeufelberger** [Wuild/GatherLite#38]
If for example I see a herb, run towards it and click on it, but only get the "you need to learn Herbalism" error message, I would expect that this addon still records the coordinates of this resource node.

Similar for chests and ores, as soon as I'm close enough to attempt opening/looting/gathering the node, it should be recorded, no matter if it was an actually successful attempt or not.

**Comment by Wuild** [comment]
This is currently not possible
We look at what spell your character is casting when mining or picking flowers etc
If this isn't triggered we cannot register the node, and even if we where we wouldnt know what icon to place since we look at the loot table and picks the first item as the icon
