### ISSUE TITLE
Nodes registered on wrong map

### ISSUE THREAD

**Issue by netlore** [Wuild/GatherLite#41]
Playing on Classic, one of my guild members reported seeing a firebloom showing up in the barrens... which I located, but I was in Tanaris at the time.  When I looked, I can't see the node in Tanaris, but I can see it in The Barrens, but it is shown as being located by the other member!
![unknown](https://user-images.githubusercontent.com/457759/64217552-bbff8b80-ceb5-11e9-9d21-cf6bb5c1e621.jpg)
![Screenshot from 2019-09-04 01-42-11](https://user-images.githubusercontent.com/457759/64217561-c3269980-ceb5-11e9-88aa-9e0d9de28b7a.jpg)

He's also reported messages such as:- Swatter found blocked actions: [AddOn: Gatherlite]

I'm concerned that we don't contaminate the logged data.

**Comment by Wuild** [comment]
are you sure its not 2 different flowers? since its been discovered at different times and by different people?

**Comment by netlore** [comment]
I'm certain that it's not 2 different flowers, because firebloom does not spawn in The Barrens.... but also because on my Classic realm there's no one in my guild but me that's high/mad enough to be herbing in an area where firebloom does spawn.... so that is the only firebloom in the database.

One thing that's been worrying me is that most people report the @Release Version@ issue, and I'm certain that most of them don't know there's different downloads for classic vs retail... and probably they have old versions as I know you've been working hard on updating things.... is there anything that could cause issues that I need to prioritize getting people to update/fix?

It looks to me like I (Knevah) picked that flower, and another player (Levinus) rebroadcast it somewhere else... I know the timestamp doesn't seem to agree, but Levinus is way to low to pick firebloom.

**Comment by Wuild** [comment]
the @release version@ comes from github, the addon is setup to automaticly release on curseforge when i create a new release, download it from there to get the correct version values.

If you are using the version on github theres an experimental function for p2p sharing all your nodes, it's still in testing and that may be whats happening here.

**Comment by netlore** [comment]
I wonder if it's possible to add an automatic version check that occasionally pokes people to update if they have an old version, or one that's direct from GitHub... maybe tells them the correct place to get it etc... as I think a few of my guild just googled it and found the "master" download on GitHub first.... Maybe a popup with a warning if it's not a "released" version.

**Comment by Wuild** [comment]
this is fixed in 1.2.2
