### ISSUE TITLE
Icons showing up on the main screen

### ISSUE THREAD

**Issue by GrandMasterLynx** [Wuild/GatherLite#42]
![GatherLite](https://user-images.githubusercontent.com/54876848/64223693-e8f67300-cea2-11e9-9c86-c45a1465abd2.PNG)
It's from a guild member sharing nodes How do I fix this

**Comment by Wuild** [comment]
your using an older version of GatherLite, please update it to the latest version

**Comment by GrandMasterLynx** [comment]
how do I go about updating it?

**Comment by Wuild** [comment]
download the latest version from curseforge for either classic or retail

**Comment by GrandMasterLynx** [comment]
I mean do I just drag the new files into it or do I delete them

**Comment by Wuild** [comment]
id suggest that you replace all of it

**Comment by GrandMasterLynx** [comment]
so would that delete the spots I gathered already?

**Comment by Wuild** [comment]
no
they are saved in the game and not on the addon itself

**Comment by GrandMasterLynx** [comment]
oh thank god lol that sounds great okay thanks for the help
