### ISSUE TITLE
Quest Items showing up

### ISSUE THREAD

**Issue by GrandMasterLynx** [Wuild/GatherLite#44]
They shouldn't be on here since you do the quest just one time please take care of this
![Stolen](https://user-images.githubusercontent.com/54876848/64227917-3d095380-ceb3-11e9-8faf-045c7dc528c3.PNG)

**Comment by Wuild** [comment]
i can see that you are using an older version of the addon, this was fixed in version 1.1.3

**Comment by GrandMasterLynx** [comment]
Okay now I have the 1.1.7 retail and the boxes are still there and when I go over the ores n herbs the names don't pop up at all

**Comment by Wuild** [comment]
we never remove node, we just dont track new ones. Dont know what you mean by popup at all...

**Comment by GrandMasterLynx** [comment]
when you hover over the icon it will tell you what it is but for this one it doesn't

**Comment by Wuild** [comment]
did you restart the game...

**Comment by GrandMasterLynx** [comment]
Yup I even reloaded the UI the Icons show up but it doesn't give me any info other than showing me where to go

**Comment by GrandMasterLynx** [comment]
Just found out the issue I gotta recollect them for the info to pop up
