### ISSUE TITLE
Syncing between two PCs

### ISSUE THREAD

**Issue by jk100magnys** [Wuild/GatherLite#45]
Hello! Is here any way to syncing (or backup/restore/copy) database between two PCs?
Like a one PC at home, another in office?

**Comment by Wuild** [comment]
only way is to transfer the saved database in your WTF folder

**Comment by jk100magnys** [comment]
Could you show me the path to database for Mac OS and Win?

**Comment by Wuild** [comment]
dont know the OSX one
on windows its World of Warcraft/_classic_|_retail_/WTF/Account/#number/SavedVariables/GatherLite.lua

**Comment by jk100magnys** [comment]
For MacOS 
‎⁨Macintosh HD⁩ ▸ ⁨Applications⁩ ▸ ⁨World of Warcraft⁩ ▸ ⁨_classic_⁩ ▸ ⁨WTF⁩ ▸ ⁨Account⁩ ▸ ⁨....

Thank you. It works!
