### ISSUE TITLE
Gatherlite no longer showing me descriptions on maps.

### ISSUE THREAD

**Issue by Twil500** [Wuild/GatherLite#46]
Gatherlite no longer shows me descriptions on maps. I see the markers on the map but when I mouseover i no longer get a description (loot), it just highlight the icon and no description.

I also noticed that sometimes I see my markers on my minimap and then they vanish,comeback...

The addon is up to date btw (from twitch app).

**Comment by GrandMasterLynx** [comment]
Have you tried regetting them again I did that on one and the info pops up for me

**Comment by leoncard** [comment]
I'm having the same problem, this is happening after having updated the addon by replacing its file contents. I mouse hover and it doesn't show the info for some herbs. I'm not sure where it saves its database but perhaps updating the addon by this method "corrupts/erases" the node description.

**Comment by Twil500** [comment]
> Have you tried regetting them again I did that on one and the info pops up for me

I havent tried it yet, I was trying to avoid that. (I can deal without the comments, i would prefer keep the markers).

One thing that I noticed today is my most recent markers shows me the description but my old markers doesnt.

**Comment by Wuild** [comment]
This is due to some database changes, it should be fixed by finding the node once more.
