### ISSUE TITLE
GatherLite - hidden world map (Classic)

### ISSUE THREAD

**Issue by Vaneko** [Wuild/GatherLite#49]
**Describe the bug**

The world map is not displayed correctly in WoW Classic. As soon as I reload the game the issue disappears for a few minutes, sometimes just for a few seconds until the world map turns black/alpha again.
Based on my own initiative, I am absolutely sure that it is up to GatherLite since I deactivated every single AddOn in my game. In the end the issue got fixed by deactivating GatherLite.
However, since I and many other users would like to continue using this AddOn I would be very grateful if you could take a look at it.

**Screenshots**
https://ibb.co/dK3CQMN

Best regards,
Vaneko

**Comment by Wuild** [comment]
Are you using the latest release version of gatherlite from curseforge?

**Comment by netlore** [comment]
Several people in my guild have reported the map going "blank" also, with 1.1.7-classic from curseforge, it doesn't go "black", it just looks like a blank piece of textured parchment, I'll try to get a screenshot.

**Comment by netlore** [comment]
![Screenshot from 2019-09-05 23-21-05](https://user-images.githubusercontent.com/457759/64387504-158dc480-d034-11e9-8c9d-d28f64e82047.jpg)

Like that.

**Comment by Wuild** [comment]
Ah. This happens after a while correct?

**Comment by vprokofev** [comment]
Affected by same bug. It became worse after i enabled guild share option - now map goes blank after couple of minutes, fixed by /reload. Maybe map goes blank after some number of new nodes have been discovered?

**Comment by Wuild** [comment]
this should now be fixed in the latest version 1.2.0 on curseforge
