### ISSUE TITLE
Tracking icons bug out and fill the right half of my screen

### ISSUE THREAD

**Issue by jboulter11** [Wuild/GatherLite#5]
![WoWScrnShot_082819_082907](https://user-images.githubusercontent.com/6633472/63870242-70595900-c96e-11e9-93f9-65b37f74a8d1.jpg)

I'm seeing tracking icons all over my screen.  They don't move at all.  Happens even with disabling all other addons.

Let me know if I can give any more info to help diagnose.

**Comment by Wuild** [comment]
that is wierd... i'll look into it.

**Comment by jboulter11** [comment]
It didn't happen day one, but as I got more nodes it started happening yesterday.  Let me know if you need anything.

**Comment by Wuild** [comment]
are you using some kind of map addon?

**Comment by jboulter11** [comment]
I am using SexyMap here but it happens if I disable all addons besides GatherLite too.

**Comment by Wuild** [comment]
please try the latest master version here on github see if the error persists

download zip -> unzip -> overwrite existing files
do /reload <-- ingame

**Comment by jboulter11** [comment]
You're awesome!  Fixed!

**Comment by Wuild** [comment]
gr8

**Comment by jboulter11** [comment]
Looks like it came back right after I took a zeppelin from UC to Org.

**Comment by Wuild** [comment]
wierd... it shouldnt happen...

**Comment by Wuild** [comment]
how many nodes have you discovered?

**Comment by Malketh** [comment]
Having the same problem. 50+ nodes at this point.  Icons are fine when I'm on the Eastern Kingdom, but the second I load into Kalimdor they go nuts.

**Comment by Wuild** [comment]
ive got around 180 and havnt had this issue... and i cant find a reason for it to appear.... maybe i need to change continent aswell XD

**Comment by Erdschatten** [comment]
Seems to happen always if you go from Eastern Kingdom to Kalimdor.
For me it worked fine until I had to travel for my druids quest (waterform) to the silverpine forest.
After I travelled back the same error happened to me.

**Comment by Wuild** [comment]
ill try it out

**Comment by Wuild** [comment]
ive been going back a forth kalimdor and eastern kingdom for a while and i cannot replicate your bug...

**Comment by bobotheklown** [comment]
Would also like to report this happening. Even seen it with quest icons from my map as well as gathering nodes. I verified that disabling gatherlite addon removes the quest icon from the right side of my screen and re-enabling puts it back.

**Comment by Wuild** [comment]
throwing out a new update. please try and come back to me

**Comment by Malketh** [comment]
Still there, sadly. :(

**Comment by Wuild** [comment]
it gotta be the minimap then...

**Comment by Wuild** [comment]
new version again, please try it out :)
