### ISSUE TITLE
tooltip lua error

### ISSUE THREAD

**Issue by wolfrunner86** [Wuild/GatherLite#50]
1.1.7-classic
when ever placing mouse over any node lua error pops up

Message: Interface\AddOns\GatherLite\methods.lua:477: attempt to index local 'classColor' (a nil value)
Time: Fri Sep  6 02:06:34 2019
Count: 2
Stack: Interface\AddOns\GatherLite\methods.lua:477: attempt to index local 'classColor' (a nil value)
[C]: ?
Interface\AddOns\GatherLite\methods.lua:477: in function <Interface\AddOns\GatherLite\methods.lua:447>

Locals:

**Comment by Rawh** [comment]
Same error here with 

> Message: Interface\AddOns\GatherLite\methods.lua:477: attempt to index local 'classColor' (a nil value)
> Time: Fri Sep  6 10:05:33 2019
> Count: 2
> Stack: Interface\AddOns\GatherLite\methods.lua:477: attempt to index local 'classColor' (a nil value)
> [C]: ?
> Interface\AddOns\GatherLite\methods.lua:477: in function <Interface\AddOns\GatherLite\methods.lua:447>
> 
> Locals: 

Especially when you open the map and hover over a gatherlite ore icon.

**Comment by Wuild** [comment]
this should now be fixed in the latest version 1.2.0 on curseforge
