### ISSUE TITLE
LUA error on checking old nodes

### ISSUE THREAD

**Issue by Daribon** [Wuild/GatherLite#51]
**Describe the bug**
When hovering a node collected from older version of the addon, LUA error is produced and it doesn't display what player collected it. The error seems to appear on every single node collected from around version 1.1.5. Do note that it doesn't appear on herbs collected on version 1.1.7.

The following error will appear:

Message: Interface\AddOns\GatherLite\methods.lua:497: attempt to index field 'player' (a nil value)
Time: Fri Sep  6 13:39:32 2019
Count: 143
Stack: Interface\AddOns\GatherLite\methods.lua:497: attempt to index field 'player' (a nil value)
Interface\AddOns\GatherLite\methods.lua:497: in function <Interface\AddOns\GatherLite\methods.lua:484>

Locals: (*temporary) = nil
(*temporary) = <table> {
 [Fadeleaf] = <table> {
 }
}
(*temporary) = "[Fadeleaf]"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = GatherLiteTooltip {
 TopOverlay = <unnamed> {
 }
 updateTooltip = 0.200000
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 comparing = false
 0 = <userdata>
}
(*temporary) = "[Fadeleaf]"
(*temporary) = "x2"
(*temporary) = <userdata>
(*temporary) = "22"
(*temporary) = ":"
(*temporary) = "36"
(*temporary) = ":"
(*temporary) = "12"
(*temporary) = ""
(*temporary) = 12
(*temporary) = "attempt to index field 'player' (a nil value)"
_GatherLite = <table> {
 spellIDs = <table> {
 }
 frames = <table> {
 }
 classColours = <table> {
 }
 UpdateInterval = 1
 defaultConfigs = <table> {
 }
 showingTooltip = true
 version = "1.2.0"
 minimapFrame = <unnamed> {
 }
 minimap = GatherLite_MinimapButton {
 }
 tooltip = GatherLiteTooltip {
 }
 updateMiniMapPosition = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:46
 mainFrame = <unnamed> {
 }
 tracker = <table> {
 }
 showTooltip = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:26
 gatherSpellRanges = <table> {
 }
 name = "GatherLite"
 nodes = <table> {
 }
 isClassic = true
 hideTooltip = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:40
 TimeSinceLastUpdate = 0.542000
}
f = herbalismworldmap248 {
 0 = <userdata>
 texture = <unnamed> {
 }
}
node = <table> {
 GUID = "Player-4476-014C6A53"
 type = "herbalism"
 date = <table> {
 }
 name = "Fadeleaf"
 position = <table> {
 }
 target = "fadeleaf"
 loot = <table> {
 }
 icon = 134193
 spellID = 2366
}
lootTable = true

**To Reproduce**
1. Go to map
2. Hover over an old collected node.
3. See error

**Screenshots**
![Wow_bdUwfHFXA3](https://user-images.githubusercontent.com/6137576/64425324-ad7ac500-d0ab-11e9-9198-a378408f76f0.png)

**Comment by Wuild** [comment]
please try 1.2.1 and report back

**Comment by Daribon** [comment]
It's fixed in 1.2.1, thanks.
