### ISSUE TITLE
Map icons remaining onscreen when map is closed

### ISSUE THREAD

**Issue by Keresee** [Wuild/GatherLite#52]
When I have the "minimap icons" option checked in interface options, there are several copper/tin vein icons that stay visible on screen with no maps open. They appear in the bottom-right quadrant of the screen. Screenshot attached. Other addons are Bartender2, ClassicCastbars, Onebag3, QuestlogEx, and VendorPrice. The issue occurred before I installed ElvUI unit frames.
![Untitled](https://user-images.githubusercontent.com/55000005/64453029-9fca3d00-d0b5-11e9-996d-28fea089afbc.png)

**Comment by Wuild** [comment]
what version of the addon are you using?

**Comment by Keresee** [comment]
The latest update in the README that I have is 1.0.15

**Comment by Wuild** [comment]
if you hover the minimap icon it should say what version ur using.

**Comment by Keresee** [comment]
It says @project-version@

**Comment by Wuild** [comment]
id recommend you not using the github version and use the latest version from curseforge instead, since curseforge parses some data into the addon upon release.

**Comment by Keresee** [comment]
Ok, thank you.

**Comment by CardaNL** [comment]
I had the same problem as OP. The curseforge version solved the problem (confirmed)
