### ISSUE TITLE
Icons on Main Map Screen

### ISSUE THREAD

**Issue by GrandMasterLynx** [Wuild/GatherLite#53]
When you go to your map the icons show up on the map

![bug 3](https://user-images.githubusercontent.com/54876848/64454196-5f1ff300-d0b8-11e9-8d51-b3a40cc1cf81.PNG)

**Comment by Wuild** [comment]
it's a known bug, still looking into it

**Comment by GrandMasterLynx** [comment]
okay cool thanks for the heads up

**Comment by Wuild** [comment]
this is fixed in 1.2.2
