### ISSUE TITLE
Icons Disappear from Mini Map

### ISSUE THREAD

**Issue by GrandMasterLynx** [Wuild/GatherLite#54]
When I get closer the Icon disappears

![bug 1](https://user-images.githubusercontent.com/54876848/64454243-7ced5800-d0b8-11e9-8826-5939053fefc4.PNG)
![bug 2](https://user-images.githubusercontent.com/54876848/64454247-7e1e8500-d0b8-11e9-986f-02453afbe6e7.PNG)

**Comment by Wuild** [comment]
this is by design, it can be turned off in the interface settings.

**Comment by GrandMasterLynx** [comment]
oh okay makes sense since when you're that close your ability would kick in showing the yellow dot saying yup there's one over here
