### ISSUE TITLE
Quest Items showing up

### ISSUE THREAD

**Issue by GrandMasterLynx** [Wuild/GatherLite#55]
Quest items are showing up when I gather stuff for a Quest

![quest items](https://user-images.githubusercontent.com/54876848/64454453-fedd8100-d0b8-11e9-99bf-3bb766fc2269.PNG)
![Stolen](https://user-images.githubusercontent.com/54876848/64454454-ff761780-d0b8-11e9-93e8-ddbdc3b4bd96.PNG)

**Comment by Wuild** [comment]
You'r still using an outdated addod

**Comment by GrandMasterLynx** [comment]
I updated to the latest one when you told me to update the last time what's the current version?

**Comment by GrandMasterLynx** [comment]
I have the 1.2.1 version it wouldn't show up in game till I renamed the folder GatherLite but the Quest Icons are still there
