### ISSUE TITLE
Delete Icons & Quest Items Category

### ISSUE THREAD

**Issue by GrandMasterLynx** [Wuild/GatherLite#56]
Would be nice to have the ability to delete any Icons you want that won't effect other players maps that you share nodes with if that's even possible

have Quest type items have its own category if we can't delete items or both options would be good

the reason for the Quest Items Category is I don't need quest items showing up on my map when I'm doing quests since I will never do them again besides that's what's Questie is for

![quest items](https://user-images.githubusercontent.com/54876848/64454522-30564c80-d0b9-11e9-8247-61a4465bc69b.PNG)
![Stolen](https://user-images.githubusercontent.com/54876848/64454527-32201000-d0b9-11e9-80f3-2d587f0b76dc.PNG)

**Comment by Wuild** [comment]
your still using an outdated version of the addon.

**Comment by GrandMasterLynx** [comment]
I just installed the one that was updated 8 hours ago and the icons for the quests are still their and my guild member found them
