### ISSUE TITLE
Version 1.2.1

### ISSUE THREAD

**Issue by GrandMasterLynx** [Wuild/GatherLite#57]
When I loaded up this version it didn't show up till I renamed the folder back to GatherLite & the quest icons are still showing up for me

I'm sorry for having this issue I just want to be able to help others having the same issues as me so I can help my guild mates

**Comment by GrandMasterLynx** [comment]
![GatherLite1](https://user-images.githubusercontent.com/54876848/64457562-ecffdc00-d0c0-11e9-985b-97d4f449b11c.PNG)

**Comment by GrandMasterLynx** [comment]
![GatherLite2](https://user-images.githubusercontent.com/54876848/64457669-3a7c4900-d0c1-11e9-95cd-15fd976a4033.PNG)

**Comment by Wuild** [comment]
send me your saved variables please

**Comment by Wuild** [comment]
also i dont recommend you using the github version, download the latest stable release from curseforge instead and you will get the proper version name on the addon

**Comment by Wuild** [comment]
this is fixed in 1.2.2

**Comment by GrandMasterLynx** [comment]
> send me your saved variables please

How do I go about doing that I never really used GitHub before
