### ISSUE TITLE
Upgrading from 1.1.7-classic to 1.2.2

### ISSUE THREAD

**Issue by netlore** [Wuild/GatherLite#58]
Many nodes were deleted / became invisible when upgrading from 1.1.7-classic to 1.2.2

Is this expected behaviour?

Most of my nodes were collected with older versions 1.1.3-1.1.7

**Comment by Wuild** [comment]
this is expected since i restructured the database a bit and added a node sanitizer, so if it detects a faulty node it will remove it.
