### ISSUE TITLE
Minimap Button Visibility State not "loading"

### ISSUE THREAD

**Issue by ghost** [Wuild/GatherLite#59]
So, the Minimap Icon can be hidden by unchecking the "Show Minimap Button" option, but it seems like the state of the button visibility isnt checked on /reload.

I have checked the settings file / lua in the WTF folder and it indeed seems like the variable "["minimapButton"]" is set to false, but still the button shows up everytime I login / reload.

**Comment by Wuild** [comment]
thank you, this has been fixed in the next release
