### ISSUE TITLE
Suggestion: Visual cue while "find" is active.

### ISSUE THREAD

**Issue by adamk33n3r** [Wuild/GatherLite#6]
When "finding" herbs for example it shows a yellow dot on the minimap. With the icons from this addon they are covered. Setting the transparency of the icons is a workaround but it would be nice if there was something more "built in".

Great addon by the way, couldn't get gathermate working but this works great!

**Comment by Wuild** [comment]
in the latest version they are hidden when closer then 70 yards from the node

**Comment by adamk33n3r** [comment]
Oh my bad, I didn't realize there were updates as the changelog wasn't updated! Thank you

**Comment by Wuild** [comment]
sorry im kinda bad at writing the changelog :)
