### ISSUE TITLE
CurseForge Download Link

### ISSUE THREAD

**Issue by GrandMasterLynx** [Wuild/GatherLite#60]
When I go to download the latest update the download gives me the 1.1.7 Retail

not sure if it has the current update in it and the name hasn't been changed to reflect the new update

**Comment by Wuild** [comment]
1.2.2 is the latest one

**Comment by GrandMasterLynx** [comment]
This is what I get when I go and download it ![download](https://user-images.githubusercontent.com/54876848/64480786-3bce7400-d19c-11e9-8d1f-115347a82f68.PNG)

**Comment by Wuild** [comment]
1.1.7 is the latest for retail, go into the files tab on curseforge
