### ISSUE TITLE
New global errors with 1.2.4-classic

### ISSUE THREAD

**Issue by hemovalencia** [Wuild/GatherLite#61]
Just installed the update and am getting these errors, as soon as I enter the game. 
No nodes show on either the minimap nor on the map. 

**Error #1**

Date: 2019-09-08 01:57:11
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\GatherLite\Scripts\methods.lua line 823:
   attempt to index global 'GatherLiteGlobalSettings' (a nil value)
Debug:
   GatherLite\Scripts\methods.lua:823: sanitizeDatabase()
   GatherLite\GatherLite.lua:36:
      GatherLite\GatherLite.lua:32
   [C]: ?
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:613:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.04
  AtlasLootClassic, vv1.1.9-beta
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.8.6
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  ClassicCastbars, vv1.0.4
  ClassicCastbarsOptions, v
  ClassicCodex, v1.2.1
  ClassicThreatMeter, v1.06
  DBMCore, v1.13.6
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  ElkBuffBars, v2.6.0-195
  GatherLite, v1.2.4-classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=3c8)

**Error #2**

Date: 2019-09-08 01:42:15
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\GatherLite\Scripts\settings.lua line 53:
   attempt to index field 'minimap' (a nil value)
Debug:
   GatherLite\Scripts\settings.lua:53: member()
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:221:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:169
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1202:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1648: FeedGroup()
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1573:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1557
   [C]: ?
   ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:72:
      ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:70
   ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:287: Fire()
   ...libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:156: SelectTab()
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1684: FeedGroup()
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1928: Open()
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1956:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1954
   [C]: ?
...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:72:
      ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:70
   ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:287: Fire()
   ...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:20:
      ...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:19
   [C]: Show()
   ..\FrameXML\InterfaceOptionsFrame.lua:28: InterfaceOptionsList_DisplayPanel()
   ..\FrameXML\InterfaceOptionsFrame.lua:46: InterfaceOptionsListButton_OnClick()
   [string ":OnClick"]:2:
      [string ":OnClick"]:1
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.1.7-beta1
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.8.5
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  ClassicCastbars, vv1.0.3
  ClassicCastbarsOptions, v
  ClassicCodex, v1.2.1
  ClassicThreatMeter, v1.04
  DBMCore, v1

**Comment by hemovalencia** [comment]
To make it even weirder, it's trying to interact with Questie when i don't even use Questie nor have it installed.

Date: 2019-09-08 02:37:30
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\GatherLite\Scripts\methods.lua line 882:
   attempt to index global 'Questie' (a nil value)
Debug:
   GatherLite\Scripts\methods.lua:882: OnTooltipShow()
   ...ce\AddOns\Atlas\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:74:
      ...ce\AddOns\Atlas\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60
   [C]: ?
Locals:
tooltip = LibDBIconTooltip {
 0 = <userdata>
 updateTooltip = 0.200000
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 TopOverlay = <unnamed> {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = LibDBIconTooltip {
 0 = <userdata>
 updateTooltip = 0.200000
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 TopOverlay = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = <table> {
}
(*temporary) = 0
(*temporary) = "attempt to index global 'Questie' (a nil value)"
_GatherLite = <table> {
 spellIDs = <table> {
 }
 showingTooltip = false
 hideTooltip = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:26
 showTooltip = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:12
 version = "1.2.4-classic"
 tooltip = GatherLiteTooltip {
 }
 frames = <table> {
 }
 classColours = <table> {
 }
 tracker = <table> {
 }
 name = "GatherLite"
 gatherSpellRanges = <table> {
 }
 isClassic = true
 nodes = <table> {
 }
 UpdateInterval = 1
 configsDefaults = <table> {
 }
 TimeSinceLastUpdate = 0
}

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.04
  AtlasLootClassic, vv1.1.9-beta
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.8.6
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  ClassicCastbars, vv1.0.4
  ClassicCastbarsOptions, v
  ClassicCodex, v1.2.1
  ClassicThreatMeter, v1.06
  DBMCore, v1.13.6
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  ElkBuffBars, v2.6.0-195
  Enchantrix, v8.2.6392 (SwimmingSeadragon)
  GatherLite, v1.2.4-classic
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixMaps, v1.13.28
  LeatrixPlus, v1.13.27
  MapCoords, v0.31c
  OmniCC, v8.1.1
  PerlArcaneBar, v
  PerlCombatDisplay, v
  PerlConfig, v
  PerlFocus, v
  PerlParty, v
  PerlPartyPet, v
  PerlPartyTarget, v
  PerlPlayer, v
  PerlPlayerPet, v
  PerlTarget, v
  PerlTargetTarget, v
  RealMobHealth, v2.5
  SexyMap, vv3-classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.0.5.11302
  TitanClassicAmmo, v1.0.5.11302
  TitanClassicBag, v1.0.5.11302
  TitanClassicClock, v1.0.5.11302
  TitanClassicGold, v1.0.5.11302
  TitanClassicLocation, v1.0.5.11302
  TitanClassicLootType, v1.0.5.11302
  TitanClassicPerformance, v1.0.5.11302
  TitanClassicRepair, v1.0.5.11302
  TitanClassicVolume, v1.0.5.11302
  TitanClassicXP, v1.0.5.11302
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=6e1)

**Comment by Wuild** [comment]
please try the latest version 1.2.5 and report back

**Comment by Wuild** [comment]
noticed some more errors.
this is fixed in 1.2.7
