### ISSUE TITLE
1.2.7 Update - Icon Menu not showing

### ISSUE THREAD

**Issue by GrandMasterLynx** [Wuild/GatherLite#62]
I just downloaded the latest one and now I don't see the Icon to pick what I want showing up on the map

![GatherLite5](https://user-images.githubusercontent.com/54876848/64487357-67d30f00-d207-11e9-9e95-ed193b481df0.PNG)

**Comment by Wuild** [comment]
type /gather and check it the show minimap button it checked

**Comment by GrandMasterLynx** [comment]
![GatherLite5](https://user-images.githubusercontent.com/54876848/64487401-255e0200-d208-11e9-9460-73d3dd406a34.PNG)

**Comment by Wuild** [comment]
if you click it will the button appear?

**Comment by GrandMasterLynx** [comment]
Nvm for some reason it was buried behind the other 2 icons

**Comment by Wuild** [comment]
haha
:)

**Comment by GrandMasterLynx** [comment]
Just had to click hold n drag them outta the way
