### ISSUE TITLE
1.2.7 Quest Items showing up

### ISSUE THREAD

**Issue by GrandMasterLynx** [Wuild/GatherLite#63]
The Quest Items are still showing up for me can you add a way for me to delete them off the map?

![still showing](https://user-images.githubusercontent.com/54876848/64487467-2e030800-d209-11e9-95a1-cb64ec9fda5d.PNG)

**Comment by Wuild** [comment]
great ill add it to the sanitizer

**Comment by GrandMasterLynx** [comment]
Thanks I love GatherLite it's really helpful keep on doing what you're doing

don't know if its possible to have it not pick up quest items since you won't be recollecting them

**Comment by Wuild** [comment]
Please send me your saved variables 
#64 follow these instructions

**Comment by GrandMasterLynx** [comment]
Heres the files you asked for
[GatherLite.zip](https://github.com/Wuild/GatherLite/files/3588025/GatherLite.zip)

**Comment by GrandMasterLynx** [comment]
the lua file

[GatherLite.zip](https://github.com/Wuild/GatherLite/files/3588026/GatherLite.zip)

**Comment by Wuild** [comment]
Thank you, unfortunately i cannot sanitize the old quest item that got tracked. so either reset your treasures or leave them be
