### ISSUE TITLE
Still Errors after 1.2.7

### ISSUE THREAD

**Issue by hemovalencia** [Wuild/GatherLite#64]
I updated to 1.2.7 after your replies, upon logging back in, I immediately got the exact same error as one of the previous ones. Also of note, the gatherlite button around the minimap is gone. 

Date: 2019-09-08 07:56:04
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\GatherLite\Scripts\methods.lua line 829:
   attempt to index global 'GatherLiteGlobalSettings' (a nil value)
Debug:
   GatherLite\Scripts\methods.lua:829: sanitizeDatabase()
   GatherLite\GatherLite.lua:81:
      GatherLite\GatherLite.lua:77
   [C]: ?
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:353: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:380: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:695:
      ..\FrameXML\UIParent.lua:658
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.04
  AtlasLootClassic, vv1.1.9-beta
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.8.7
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  ClassicCastbars, vv1.0.4
  ClassicCastbarsOptions, v
  ClassicCodex, v1.2.1
  ClassicThreatMeter, v1.06
  DBMCore, v1.13.6
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  ElkBuffBars, v2.6.0-195
  GatherLite, v1.2.7-classic
  LeatrixMaps, v1.13.28
  LeatrixPlus, v1.13.27
  MapCoords, v0.31c
  OmniCC, v8.1.1
  PerlArcaneBar, v
  PerlCombatDisplay, v
  PerlConfig, v
  PerlFocus, v
  PerlParty, v
  PerlPartyPet, v
  PerlPartyTarget, v
  PerlPlayer, v
  PerlPlayerPet, v
  PerlTarget, v
  PerlTargetTarget, v
  RealMobHealth, v2.5
  SexyMap, vv3-classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.0.5.11302
  TitanClassicAmmo, v1.0.5.11302
  TitanClassicBag, v1.0.5.11302
  TitanClassicClock, v1.0.5.11302
  TitanClassicGold, v1.0.5.11302
  TitanClassicLocation, v1.0.5.11302
  TitanClassicLootType, v1.0.5.11302
  TitanClassicPerformance, v1.0.5.11302
  TitanClassicRepair, v1.0.5.11302
  TitanClassicVolume, v1.0.5.11302
  TitanClassicXP, v1.0.5.11302
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=68a)

**Comment by Wuild** [comment]
could you send me your saved variables from
World of Warcraft/_classic|retail_/WTF/Account/**account**/SavedVariables/GatherLite.lua

**Comment by hemovalencia** [comment]
k, new here, do i PM you them?

**Comment by hemovalencia** [comment]
zipped it since LUA can't be sent on this
[GatherLite.zip](https://github.com/Wuild/GatherLite/files/3587591/GatherLite.zip)

**Comment by Wuild** [comment]
I see the problem, thanks it will be fixed in the next release.

**Comment by hemovalencia** [comment]
no problem, thanks for the quick replies.

**Comment by Wuild** [comment]
new version has been uploaded

**Comment by hemovalencia** [comment]
will let you know as soon as i can, servers are down at the moment.

**Comment by Wuild** [comment]
Great! thanks!

**Comment by hemovalencia** [comment]
Logged in with the 1.2.9 version update, still unfortunately getting the same error message. 

Date: 2019-09-08 11:00:33
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\GatherLite\Scripts\methods.lua line 806:
   attempt to index global 'GatherLiteGlobalSettings' (a nil value)
Debug:
   GatherLite\Scripts\methods.lua:806: sanitizeDatabase()
   GatherLite\GatherLite.lua:81:
      GatherLite\GatherLite.lua:77
   [C]: ?
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:613:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605
Locals:
None


no idea what is causing it, as i know nothing about coding for mods.

**Comment by hemovalencia** [comment]
i removed the lower portion of addons listed, if needed i can add

**Comment by Wuild** [comment]
no need

**Comment by Wuild** [comment]
please try 1.2.12

**Comment by hemovalencia** [comment]
1.2.12, same thing.

Date: 2019-09-08 11:06:48
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\GatherLite\Scripts\methods.lua line 808:
   attempt to index global 'GatherLiteGlobalSettings' (a nil value)
Debug:
   GatherLite\Scripts\methods.lua:808: sanitizeDatabase()
   GatherLite\GatherLite.lua:81:
      GatherLite\GatherLite.lua:77
   [C]: ?
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:613:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605
Locals:
None

is it a conflict between mods?

**Comment by Wuild** [comment]
kk uploading new version now

**Comment by hemovalencia** [comment]
hey, no errors upon login, i'm gonna go hit some resources and see if they show up on the maps. 
also, the minimap button has returned, looking good so far!

**Comment by Wuild** [comment]
Great! keep in touch ;)

**Comment by hemovalencia** [comment]
that did it, working like a charm, recorded both gathered mining resource and a treasure chest i happened upon. they show up on both map and minimap as well, no error messages whatsoever!

**Comment by Wuild** [comment]
ill consider this resolved then :)

**Comment by budgej** [comment]
Hi, I'm still getting a similar error.

Date: 2019-09-14 09:27:55
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\GatherLite\GatherLite.lua line 77:
   attempt to index global 'GatherLite' (a nil value)
Debug:
   GatherLite\GatherLite.lua:77: in main chunk
Locals:
name = "GatherLite"
_GatherLite = <table> {
 showingTooltip = false
 tooltip = GatherLiteTooltip {
 }
 hideTooltip = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:26
 showTooltip = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:12
}
minimapIcon = <table> {
}
(*temporary) = nil
(*temporary) = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:77
(*temporary) = <table> {
}
(*temporary) = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
(*temporary) = nil
(*temporary) = nil
(*temporary) = "GatherLiteMinimapIcon"
(*temporary) = "attempt to index global 'GatherLite' (a nil value)"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.1.9-beta
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  BagFreeSpaceCounter, v1.0.2
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  ClassicCastbars, vv1.0.4
  ClassicCastbarsOptions, v
  Combuctor, v8.2.6
  GatherLite, v@project-version@
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=30a)
