### ISSUE TITLE
No nodes in Darkshore / No MiniMap icon

### ISSUE THREAD

**Issue by fnordson** [Wuild/GatherLite#65]
**Describe the bug**
No MiniMap icon
No copper nodes in Darkshore 

**To Reproduce**
1. Go to 'Darkshore'
2. Click on 'Iron Node'
3. ???
4. See nothing

**Expected behavior**
A node should appear on the MiniMap

**Additional context**
AddOn Version: 1.2.12-classic
This is my first installation of this addon 
We had Gathermate before but switched because we had the same issue with Darkshore. 
My guess is that it is maybe something related to the client language. We use the German client and the name there is "Dunkelküste". 
_(I don't know if it's the same issue in other zones since I don't have another miner and this one is low so I can't really roam the neighbouring zones)_

However, why the MiniMap icon is not there is a different  problem and probably not related (it's activated in the options)

**Comment by Wuild** [comment]
Try 1.2.13

**Comment by fnordson** [comment]
MiniMap icon is there. 
I'll report when I find a node.

**Comment by Wuild** [comment]
Thanks!

**Comment by fnordson** [comment]
Nodes showing. 
Perfect! 
Thank you. :)

**Comment by Wuild** [comment]
Great! thanks for using my addon

**Comment by fnordson** [comment]
Thanks for making it. 
We'll stay with it now :)
