### ISSUE TITLE
my issue with gatherlite is that herbs icons from the map are on my game screen 

### ISSUE THREAD

**Issue by Nuubi08** [Wuild/GatherLite#66]
**Describe the bug**
my issue with gatherlite is that herbs icons from the map are on my game screen 
**To Reproduce**
i dont know how to reproduce it
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Wuild** [comment]
what version of the addon are you using?

**Comment by Nuubi08** [comment]
1.13
i downloaded it here : 
https://legacy-wow.com/classic-addons/gatherlite/

**Comment by Wuild** [comment]
do not download it from legacy wow, i dont know how it got there but i'm not maintaning it there... download it from curseforge https://www.curseforge.com/wow/addons/gatherlite/files version 1.2.13

**Comment by Nuubi08** [comment]
it works ! Thank you for help :)
