### ISSUE TITLE
Plants icon popping out of the map

### ISSUE THREAD

**Issue by Ash-Cucumbear** [Wuild/GatherLite#67]
Just take a look at my screenshot;

Some of my plants are simply in the middle of my screen. 

Question 1: how to remove them?
Question 2: how to update the addon without losing my database?

![WoWScrnShot_090919_101354](https://user-images.githubusercontent.com/55070862/64499193-9bd33080-d2ea-11e9-8719-cec341fd0534.jpg)
![WoWScrnShot_090919_101414](https://user-images.githubusercontent.com/55070862/64499194-9bd33080-d2ea-11e9-9a77-b93394ee0478.jpg)

**Comment by ghost** [comment]
I couldn't see his screenshots, but I believe I'm also having this problem.
Tried disabling and reenabling the addon but they keep popping up here in the same spot
![plants](https://user-images.githubusercontent.com/55077659/64507621-3579ee00-d2a9-11e9-9e3d-57272ab355de.png)

**Comment by Wuild** [comment]
what version of the addon are you guys using?
Make sure it's downloaded from the curseforge website or the twitch app, as im not uploading it anywhere else at this point.

**Comment by ghost** [comment]
the readme changelog's most recent update says that it's 1.0.15

**Comment by Wuild** [comment]
there is no changelog

**Comment by Wuild** [comment]
latest version is 1.2.13 for classic and 1.2.12 for retail

**Comment by ghost** [comment]
damn then i guess it's just @projectversion@

**Comment by ghost** [comment]
ah well shame to lose all my progress but I just downloaded the 1.2.13 file and i'll install that real quick.

thanks for the help!

**Comment by Wuild** [comment]
you wont lose any progress...

**Comment by ghost** [comment]
WOAH! Yup all fixed and everything is there wow your addon is incredible thanks lol

**Comment by Wuild** [comment]
Your welcome, and thank you for using my addon.
