### ISSUE TITLE
Icons showing up in Org

### ISSUE THREAD

**Issue by GrandMasterLynx** [Wuild/GatherLite#69]
Items I found in Skull Rock are showing up in Org

![icons on map](https://user-images.githubusercontent.com/54876848/64519664-8f3ae200-d2c2-11e9-9817-14ca062c0ca6.PNG)

**Comment by Wuild** [comment]
yes?

**Comment by GrandMasterLynx** [comment]
Is that supposed to be showing when I'm in the Org Map I just think it's a bit off since it looks out of place

**Comment by Wuild** [comment]
yes?

**Comment by GrandMasterLynx** [comment]
seems out of place like it's not being aesthetic to the eyes

**Comment by Wuild** [comment]
it's cuz its on the edge of the map
