### ISSUE TITLE
Node Sharing not working...

### ISSUE THREAD

**Issue by Zabeard** [Wuild/GatherLite#7]
I was in a party with the party share turned on, I see the debug message leave my character when i pick up a fish however nothing is received by my other party members.

I have checked that we are on the latest version and that we both have party share enabled.  Have used SpyDon which monitors the chat channel to see the GatherLite message leave but doesn't seemed to be received at destination?

I was in Orgrimmar and he was just outside in Durotar.

**Comment by Wuild** [comment]
wierd i'll look into it

**Comment by pquerner** [comment]
Party sync seems to work for me (party of two, me and my friend), but Guild sync does not work. I've not been able to debug this. 
Using GatherLite 1.0.32-classic.

**Comment by Wuild** [comment]
ive made some huge changes. new version is coming soon.

**Comment by pquerner** [comment]
I see its sending something, altough I cannot be sure if its from a guildy or random person.
https://i.imgur.com/TOH5SBn.png

**Comment by Wuild** [comment]
it's from a guild member.. couldnt be from a random except in a party

**Comment by pquerner** [comment]
Nope, wasnt from a party member (all afk, except me and I didnt loot anything at all since I opened SpyDon). Will check the new version once its on github or curse. Thanks!

**Comment by Wuild** [comment]
try the latest 1.1.0

**Comment by pquerner** [comment]
1.1.0 and 1.1.1 doesnt seem to send out anything anymore (tested with SpyDon). Completely clean WTF folder (so I can test it with a guildie and not see my own found nodes). (Enabled sharing of course, and also did a reload in between installations/updates)

**Comment by Wuild** [comment]
right, forgot to add the node share again XD adding it now

**Comment by pquerner** [comment]
1.1.2 works (guild share tested), same region (the barrens).

**Comment by Wuild** [comment]
gr8!
