### ISSUE TITLE
Icons showing without map open ... 

### ISSUE THREAD

**Issue by Grishnakk** [Wuild/GatherLite#71]
**Describe the bug**

Some icons of gathered stuff dont hide when closing the map again. Relogging doesnt help. Please give option to delete certain icons and look into the problem of them not hiding when closing map. Maybe give a button to toggle show icons and not show icons. 

**Expected behavior**

I expected icons to hide / close when i close my map.

**Screenshots**

[https://abload.de/img/gatherliteissue1345hcko3.jpg](url)

**Comment by Wuild** [comment]
please read this post https://github.com/Wuild/GatherLite/issues/67
