### ISSUE TITLE
Differentiate between Chests and Quest Pickups

### ISSUE THREAD

**Issue by gustavo-momente** [Wuild/GatherLite#72]
**Is your feature request related to a problem? Please describe.**
Right now it's hard do quickly look in the minimap and see if there is a nearby chest as Chests and Quest Pickups are filtered inside the same category "Treasures".

**Describe the solution you'd like**
It would be interesting to split the Treasure category into two categories, Chests (or a better name) and Quest Related Treasures. So we can choose which one to always track.

**Comment by Wuild** [comment]
this was a bug in an earlier version of GatherLite, we no longer tracks quest items altho already tracked quest items cannot detected and removed. sorry
