### ISSUE TITLE
icons displaying on screen

### ISSUE THREAD

**Issue by Knewdles** [Wuild/GatherLite#73]
**Describe the bug**

gather icons displaying on screen, they do not move/correlate with current location. reloading the addon / reload of the ui does not correct. turning it off removes the icon from the screen, returning to undercity via zep also removes icons from the screen. only occurring on west continent.

**To Reproduce**

not sure, started as undead, gathering around undercity with no issues. took a zep to orgrimmarr, now the icons are on the screen under the quest list. 

**Screenshots**

![image](https://user-images.githubusercontent.com/55214782/64739982-d0e5ab80-d4c1-11e9-9d51-9e88b56df3b2.png)

**Comment by Wuild** [comment]
please read this post https://github.com/Wuild/GatherLite/issues/67
