### ISSUE TITLE
Nodes are stuck on the interface

### ISSUE THREAD

**Issue by scoobydrew** [Wuild/GatherLite#75]
**Describe the bug**
I started using this add-on and the first 2 mining nodes I tracked are stuck on my UI when I switch areas.  I mined them in the Eastern Kingdoms and whenever I move to Kalimdor or into an instance I have two nodes stuck on the middle left of my screen, no where even near the mini-map.

**To Reproduce**
1. Go to any area
2. Mine something
3. Move into an instance or another continent.  Anything that will trigger a loading screen.
4. See the nodes randomly on the UI.

**Expected behavior**
I don't want to see these nodes.

**Screenshots**

![image](https://user-images.githubusercontent.com/1577869/65042431-706dc880-d91e-11e9-9065-1866568ea17e.png)

**Additional context**
I tried reloading gatherlite using the console commands and reloading the entire game UI.  This even happens between characters and when I first load the game on a different continent.

**Comment by Wuild** [comment]
I believe your using an older version of GatherLite, Please update your addon through curseforge or the twitch app. I'm not uploading this addon anywhere else and if you have gotten it from somewhere else i'm not the maintainer on that website. If this error still occures after updating your addon i will look into it once more.
