### ISSUE TITLE
Blank world map

### ISSUE THREAD

**Issue by triggspy** [Wuild/GatherLite#77]
**Describe the bug**
Sometimes, when I open the world map it is black/blank. This typically requires a /reloadui to resolve but sometimes I can switch zones and come back and it works. I run four addons: Auctioneer, ElvUi, GatherLite & Questie. I've taken the time to disable all except each to see which addon was failing and if when GatherLite is the only addon running, it will occur. 

Is there a way for me to fix this? Is there a way I can capture the error when it occurs in some sort of log to help diagnose? I love the plugin, but really hate having to reload my ui all the time. 

I have already disabled the worldmap skin on ElvUi. 

**To Reproduce**
1. Have Gatherer loaded
2. Hit M 
3. Intermittently the screen will be blank/black

**Expected behavior**
The map appears. 

**Screenshots**
https://imgur.com/VThMMrl

**Additional context**

**Comment by Wuild** [comment]
I believe your using an older version of GatherLite, Please update your addon through curseforge or the twitch app. I'm not uploading this addon anywhere else and if you have gotten it from somewhere else i'm not the maintainer on that website. If this error still occures after updating your addon i will look into it once more.

**Comment by triggspy** [comment]
Wow, thank you for the fast response. I will update and follow up.

**Comment by Wuild** [comment]
Thanks

**Comment by triggspy** [comment]
While I got you here - are there any ways I could download a data file that show me where other people have gathered stuff?

**Comment by Wuild** [comment]
Not at this point. it's beeing worked on though

**Comment by triggspy** [comment]
Been about 20 minutes with no issues, that must have fixed it. Thank you!

**Comment by Wuild** [comment]
I'll consider this closed then, just write if the error occures again
