### ISSUE TITLE
Chinese lua error

### ISSUE THREAD

**Issue by Spiricore** [Wuild/GatherLite#79]
Hi there, thanks so much for working on this addon! I'm an english user but I've been getting this error since the simplified chinese (and others) update:

11x GatherLite\Locale\zhCN-Simplified Chinese.lua:2: attempt to index local 'L' (a nil value)
GatherLite\Locale\zhCN-Simplified Chinese.lua:2: in main chunk

Locals:
L = nil
(*temporary) = <table> {
 apps = <table> {
 }
 GetLocale = <function> defined @AddOnSkins\Libs\Ace3\AceLocale-3.0\AceLocale-3.0.lua:132
 NewLocale = <function> defined @AddOnSkins\Libs\Ace3\AceLocale-3.0\AceLocale-3.0.lua:93
 appnames = <table> {
 }
}
(*temporary) = "GatherLite"
(*temporary) = "zhCN"
(*temporary) = "attempt to index local 'L' (a nil value)"

**Comment by Wuild** [comment]
This has been fixed in the next version
