### ISSUE TITLE
Icons are on Screen while Map is closed

### ISSUE THREAD

**Issue by Itroll91** [Wuild/GatherLite#8]
I have just Herbs activated. On right side of Screenshot you can see the Icons,

![WoWScrnShot_083019_053447](https://user-images.githubusercontent.com/54697160/63991608-c225ee80-cae8-11e9-9f53-b97b6ec50edd.jpg)

**Comment by Itroll91** [comment]
New version has fixed it. Nice Work! Thank you verry verry much! Maybe it will be possible to get something like the Mod "Routes" to work with on classic? That woud be awsome!

**Comment by Wuild** [comment]
dont know what that is :) 
great that it's fixed!
