### ISSUE TITLE
Randomly placed nodes

### ISSUE THREAD

**Issue by karunama** [Wuild/GatherLite#80]
![WoWScrnShot_091819_040538](https://user-images.githubusercontent.com/55490008/65143550-1aeef580-d9ca-11e9-842c-a3527b8a38f4.jpg)
Nodes that should be on the minimap instead are appearing elsewhere on the screen, apparently random in placement.  The place is the same all throughout each continent (as far as I can tell) but differs between the continents.  That is to say if I see earthroot at the top of my screen in Darnassus, it will still be there in Ratchet.  If I take the boat to Booty Bay, however, I might see a kingsblood in the middle of my screen.  Not sure what causes it, but it may be a result of having used a different UI briefly (GW2UI)

**Comment by Wuild** [comment]
I believe your using an older version of GatherLite, Please update your addon through curseforge or the twitch app. I'm not uploading this addon anywhere else and if you have gotten it from somewhere else i'm not the maintainer on that website. If this error still occures after updating your addon i will look into it once more.
