### ISSUE TITLE
Newest version for classic does not show any map icons

### ISSUE THREAD

**Issue by ScarrP2S** [Wuild/GatherLite#81]
I updated the addon, no map icons.   I reverted to prior install but getting a few LUA errors on it.

**Comment by Wuild** [comment]
what version did you update from?

**Comment by ScarrP2S** [comment]
The previously available version as of yesterday.  I use the Twitch app for mods and update them daily.

**Comment by Wuild** [comment]
thats wierd... you mind sending me ur SavedVariables files so i can check it out?

**Comment by ScarrP2S** [comment]
1.3.0 classic shows the icons for nodes I have collected prior to this latest update... however when I use that version I get the following LUA errors.

1) 
Message: Interface\AddOns\GatherLite\Locale\zhCN.lua:2: attempt to index local 'L' (a nil value)
Time: Wed Sep 18 08:18:13 2019
Count: 1
Stack: Interface\AddOns\GatherLite\Locale\zhCN.lua:2: attempt to index local 'L' (a nil value)
Interface\AddOns\GatherLite\Locale\zhCN.lua:2: in main chunk

Locals: L = nil
(*temporary) = <table> {
 apps = <table> {
 }
 GetLocale = <function> defined @Interface\AddOns\Atlas\Libs\AceLocale-3.0\AceLocale-3.0.lua:132
 NewLocale = <function> defined @Interface\AddOns\Atlas\Libs\AceLocale-3.0\AceLocale-3.0.lua:93
 appnames = <table> {
 }
}
(*temporary) = "GatherLite"
(*temporary) = "zhCN"
(*temporary) = "attempt to index local 'L' (a nil value)"

2)
Message: (null)
Time: Wed Sep 18 08:18:15 2019
Count: 4

**Comment by Wuild** [comment]
so 1.3.0 works except that error and 1.3.1 doesnt?

**Comment by ScarrP2S** [comment]
Correct

**Comment by ScarrP2S** [comment]
[Scarr-GatherLite.zip](https://github.com/Wuild/GatherLite/files/3626340/Scarr-GatherLite.zip)

**Comment by ScarrP2S** [comment]
above is my saved variables .lua file

**Comment by Wuild** [comment]
I fixed it.. pushing a new release

**Comment by ScarrP2S** [comment]
great, thanks!

**Comment by Wuild** [comment]
Also please consider publishing your database to
https://gatherlite.labcake.org/

**Comment by Wuild** [comment]
1.3.2 is published, please try it and report back

**Comment by ScarrP2S** [comment]
I uploaded my file to your repository database.

**Comment by Wuild** [comment]
great! thanks!

**Comment by ScarrP2S** [comment]
Updated it, works fine, no LUA errors and I can see my nodes again.  Thanks!

**Comment by Wuild** [comment]
i'll consider this as closed then
