### ISSUE TITLE
Not showing any icons after looting?

### ISSUE THREAD

**Issue by 4thCavScout** [Wuild/GatherLite#82]
Date: 2019-09-20 15:50:59
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\GatherLite\GatherLite.lua line 846:
   table index is nil
Debug:
   GatherLite\GatherLite.lua:846: foundTreasureChest()
   GatherLite\GatherLite.lua:932:
      GatherLite\GatherLite.lua:901
Locals:
loot = <table> {
}
count = 5
(for index) = 1
(for limit) = 5
(for step) = 1
i = 1
lIcon = 133786
lName = "1 Silver
39 Copper"
lQuantity = 0
lQuality = nil
slotType = 2
lLink = nil
(*temporary) = <table> {
 name = "1 Silver
39 Copper"
 count = 0
}
(*temporary) = 0
(*temporary) = 0
(*temporary) = "table index is nil"
GatherLite = <table> {
 spellIDs = <table> {
 }
 findSpell = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:276
 updateMiniMapPosition = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:424
 UpdateMapNodes = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:534
 debug = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:237
 handleSpell = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:854
 needMapUpdate = false
 UpdateMinimapNodes = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:585
 gatherSpellRanges = <table> {
 }
 nodes = <table> {
 }
 hideTooltip = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:306
 TimeSinceLastUpdate = 0.336000
 ParseSentData = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:751
 foundOreOrHerb = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:797
 IsNodeInRange = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:312
 minimap = GatherLite_MinimapButton {
 }
 findSpellType = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:264
 showTooltip = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:292
 name = "GatherLite"
 minimapFrame = <unnamed> {
 }
 defaultConfigs = <table> {
 }
 showingTooltip = false
 isRetail = false
 UpdateInterval = 1
 print = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:233
 classColours = <table> {
 }
 foundTreasureChest = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:839
 mainFrame = <unnamed> {
 }
 tracker = <table> {
 }
 addNode = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:321
 isClassic = true
 spawnMarker = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:436
 CopyDefaults = <function> defined @Interface\AddOns\GatherLite\GatherLite.lua:411
 nodeUpdated = false
 tooltip = GatherLiteTooltip {
 }
 version = "@project-version@"
}

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ArcHUD3classic, vclassic-v5.0.9
  AtlasLootClassic, vv1.1.9-beta
  AucAdvanced, v8.2.6420 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.8.7
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  Details, v
  DetailsTinyThreat, v
  DingPlayed, v
  Enchantrix, v8.2.6411 (SwimmingSeadragon)
  GatherLite, v@project-version@
  HealBot, v1.13.2.2
  HealBotTips, v1.13.2.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  orbSellAndRepair, v1.0.1
  Questie, v4.0.18 BETA
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=3e1)

**Comment by Wuild** [comment]
I believe your using an older version of GatherLite, Please update your addon through curseforge or the twitch app. I'm not uploading this addon anywhere else and if you have gotten it from somewhere else i'm not the maintainer on that website. If this error still occures after updating your addon i will look into it once more.
