### ISSUE TITLE
Black Lotus - Missing

### ISSUE THREAD

**Issue by wow-config** [Wuild/GatherLite#85]
**Describe the bug**
Black Lotus Lootings do not get recorded

**To Reproduce**
Loot a Black Lotus & notice how contrary to normal herbs it does not show up

**Expected behavior**
Recorded like any other herb

**Screenshots**

**Additional context**

**Comment by wow-config** [comment]
Noticed that black lotuses from winterspring are functioning correctly which just makes me wonder why the ones in burning steppes don't show up.

Another issue i had where herbs got stuck on screen i went into the wtf folder in order to manually delete all entries of kingsblood which was an icon always on screen, not minimap but literally on screen... would be nice with an option allowing players to add nodes manually at locations & remove unwanted ones.

**Comment by Wuild** [comment]
I believe your using an older version of GatherLite, Please update your addon through curseforge or the twitch app. I'm not uploading this addon anywhere else and if you have gotten it from somewhere else i'm not the maintainer on that website. If this error still occures after updating your addon i will look into it once more.
