### ISSUE TITLE
stuck icon

### ISSUE THREAD

**Issue by wow-config** [Wuild/GatherLite#86]
**Describe the bug**
Kingsblood icon permanent stuck

**To Reproduce**

Hard to pinpoint the cause however the Kingsblood icon remains in the left upper corner even when the screen is closed and appears each time i fly near the zone causing it, i assume the herb has been on the border between 2 maps sadly not able to pinpoint which herb is the cause.

Fix could be the ability to flush all of a certain herb or the ability to toggle between a list of tracked items which would be a nice feature as well, lets consider you farm ghost mushrooms or gromsblood it would be nice toggling which herbs you have focus on so the map isnt flooded.

**Comment by Wuild** [comment]
I dont understand... could you provide a screenshot?

**Comment by wow-config** [comment]
![screenshot](https://user-images.githubusercontent.com/1918875/65528962-9c2c1800-def5-11e9-8a6a-e84cf29eaa9b.jpg)

Basically that lil one hangs around like forever but funny thing is no other herb does that and when i hover over it i can see it was picked once back in 04/09/2019

**Comment by Wuild** [comment]
I believe your using an older version of GatherLite, Please update your addon through curseforge or the twitch app. I'm not uploading this addon anywhere else and if you have gotten it from somewhere else i'm not the maintainer on that website. If this error still occures after updating your addon i will look into it once more.
