### ISSUE TITLE
Nodes Toggle-able by Profession

### ISSUE THREAD

**Issue by Dejoule** [Wuild/GatherLite#87]
**Is your feature request related to a problem? Please describe.**
My map and minimap are cluttered by dots for things that do not apply to my character. IE, I'm an herbalist, and I'm seeing mining nodes everywhere

I was hoping for a toggle in the options panel to only display nodes you want. Turn minerals on/off, turn fishing on/off, etc.

We have multiple guildies all using gatherlite and collecting a lot of nodes on the map that will be useful on one character, but not on others.

The only alternative would be to switch mods, but we want to stick with the same mod to keep the database we've built.

**Comment by MarkusTeufelberger** [comment]
Isn't that what the selection you get when left-clicking on the minimap icon is for?

**Comment by Wuild** [comment]
Yes you can select what nodes to show when you click on the minimap button

**Comment by Dejoule** [comment]
So I had the minimap button disabled, sorry to waste everybody's time.

**Comment by Wuild** [comment]
No problem at all
