### ISSUE TITLE
Nodes on main screen

### ISSUE THREAD

**Issue by elvs1** [Wuild/GatherLite#88]
![2019-09-24 (2)](https://user-images.githubusercontent.com/55748310/65513592-2cf9f800-dee4-11e9-82d9-9f592a0fbd44.png)

2 copper nodes showing on main screen at all times
 Option to remove these nodes?

**Comment by Wuild** [comment]
I believe your using an older version of GatherLite, Please update your addon through curseforge or the twitch app. I'm not uploading this addon anywhere else and if you have gotten it from somewhere else i'm not the maintainer on that website. If this error still occures after updating your addon i will look into it once more.

**Comment by elvs1** [comment]
Thank you! Newest version worked for me!

Elvijs Lodiņš
