### ISSUE TITLE
Enable keybinds in addons - Key Binding

### ISSUE THREAD

**Issue by AlertedOsprey** [Wuild/GatherLite#89]
**Is your feature request related to a problem?**
No, not related to a problem.

**Please describe.**
I seem to find myself clicking on the GathererLite minimap butten, then deselect mining so I can see there is actually a mining node present on the (mini)map.
Which I find a quite tedious process to move your mouse over to the minimap and then deselect the mineral, check your map to see if a node is truly there, then after you have mined, select minerals again to turn the GathererLite back on.

**Describe the solution you'd like**
It would be nice to see a keybinds, which you can set for yourself in the Wow Menu :: "Key Bindings" > "Addons" (left menu - bottom) > "Key Bindings".
which lets you show/hide tracking of for example minerals.
Whenever you mine an icon it is shown on top of a potential node, so I am not actually sure if there is a real node underneath it. So that's why I'm desecting and re-selecting in the minimap icon.

**Additional context**
The place to set the keybinds as mentioned above via: 

Wow Menu :: "Key Bindings" > "Addons" (left menu - bottom) > "Key Bindings".

![Capture2](https://user-images.githubusercontent.com/55848818/65707908-bc8eda80-e08d-11e9-8391-83f4858748df.PNG)

![Capture](https://user-images.githubusercontent.com/55848818/65707750-746fb800-e08d-11e9-98c3-b7a06216b76c.PNG)

**Comment by Wuild** [comment]
sounds like your using an older version of the addon

**Comment by AlertedOsprey** [comment]
I'm using GatherLite-1.3.2-classic.zip

**Comment by Wuild** [comment]
then the nodes should be hidden automaticly when closer than 70 yards on default.

**Comment by AlertedOsprey** [comment]
Thanks for the tip! Playing around with the distance (slider) at the moment.
As far as for me this case can be closed
