### ISSUE TITLE
wrong icons but right tooltip

### ISSUE THREAD

**Issue by derpierre65** [Wuild/GatherLite#9]
look at this short video -> spam map (open, close, open close) and all icons are replaced after a while

https://files.derpierre65.de/30-08-2019/FlippantAgamaVibrant.mp4

tooltip is alright only the icon is wrong

edit: after /reload are replaced the wrong icons to the correct icons

**Comment by Wuild** [comment]
what version are you using?

**Comment by derpierre65** [comment]
oh sry, 1.0.27

**Comment by Wuild** [comment]
please test the latest 1.0.28-classic i may have fixed it

**Comment by derpierre65** [comment]
thanks, @Wuild can we write over discord or so?

**Comment by Wuild** [comment]
sure

Wuild#5854
