### ISSUE TITLE
Hide minimap node icons earlier?

### ISSUE THREAD

**Issue by Srljm** [Wuild/GatherLite#91]
Hi!
I have a problem with how the addon works on the minimap.

GatherLite's node icons on the minimap conflict with Blizzards yellow dots, because the range from the player where the icons automatically get hidden is too short. This means I cant see if a node has spawned under the GatherLite icon and have to go unnecessary near the spot to hide the icon.

I need a slight increase for this hide-distance.
Can you tell where to change numbers in the code so I can adjust it to my likings?

**Comment by Wuild** [comment]
theres a slider in the options panel of the addon where you can change this without altering the code.

**Comment by Srljm** [comment]
Sorry I cant find it.
There are size and opacity sliders, do you mean those? Opacity could work but naturally comes with a visibility trade off for the icons. Depending on the ground and node they can be hard to notice:
![GatherLite IconOpacity](https://user-images.githubusercontent.com/55985046/65897662-10603300-e3b0-11e9-984c-ff298d1b2b2c.png)
