### ISSUE TITLE
[Feature Request] Filter Nodes by current professions

### ISSUE THREAD

**Issue by MrBramwell** [Wuild/GatherLite#93]
Hi, first of all, thanks for a really useful addon!

I'm in a guild with well over 100 active people, and quite a few of them are using the addon, and thus, my minimap is absolutely filled with nodes.

Would it be possible to add a button to toggle "Show only my professions" or "Show only nodes related to my profession".

Then, if I'm a miner and skinner - I wouldn't have all herbs showing, I would then only see Veins on the map.

Or make each Profession toggleable, Default all ticked, then you can tick/untick, Veins, Herbs, Chests etc

**Comment by MrBramwell** [comment]
Nevermind me. I just realised you can do that using the minimap button. But perhaps it should be an option in the Options panel too ? I'm one of those that likes a clean look, and so I hide all minimap buttons

**Comment by Wuild** [comment]
it will be added to the options panel. Ive just been busy with other things.
