### ISSUE TITLE
Toggling debugging will not work ( classic )

### ISSUE THREAD

**Issue by 2damfresh** [Wuild/GatherLite#95]
Using the chat command to toggle debugging mode off creates a LUA error and will not turn off. Toggling debugging mode on worked with no issue.

The error when attempting to toggle off is while Gather lite is isolated:

Message: Interface\AddOns\GatherLite\Scripts\methods.lua:147: attempt to index global 'GGatherLite' (a nil value)
Time: Thu Oct  3 19:33:05 2019
Count: 1
Stack: Interface\AddOns\GatherLite\Scripts\methods.lua:147: attempt to index global 'GGatherLite' (a nil value)
Interface\AddOns\GatherLite\Scripts\methods.lua:147: in function `?'
...ns\GatherLite\Libs\AceConsole-3.0\AceConsole-3.0.lua:94: in function `?'
Interface\FrameXML\ChatFrame.lua:4609: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4270: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4306: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\GatherLite\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 findSpell = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:173
 ResetDatabaseType = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:1033
 EnableModule = <function> defined @Interface\AddOns\GatherLite\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\GatherLite\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @Interface\AddOns\GatherLite\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 UnregisterComm = <function> defined @Interface\AddOns\GatherLite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 debug = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:75
 Printf = <function> defined @Interface\AddOns\GatherLite\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\GatherLite\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 GatherSlash = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:138
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\GatherLite\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 insertDatabaseNode = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:333
 ScheduleTimer = <function> defined @Interface\AddOns\GatherLite\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\GatherLite\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 createNode = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:681
 RegisterMessage = <function> defined @Interface\AddOns\GatherLite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\GatherLite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 frames = <table> {
 }
 ResetDatabase = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:1019
 syncedNodes = <table> {
 }
 translate = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:61
 db = <table> {
 }
 UnregisterAllComm = <function> defined @Interface\AddOns\GatherLite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Interface\AddOns\GatherLite\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 NewVersionExists = false
 RegisterEvent = <function> defined @Interface\AddOns\GatherLite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 sanitizeNode = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:860
 IterateModules = <function> defined @Interface\AddOns\GatherLite\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 Version = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:35
 CopyDefaults = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:116
 ShowSettings = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:133
 p2pDatabase = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:915
 drawWorldmap = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:440
 Colorize = <function> defined @Interface\AddOns\GatherLite\Scripts\methods.lua:93
 Enable = <function> defined @Interfac
Interface\FrameXML\ChatFrame.lua:4270: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4306: in function <Interface\FrameXML\ChatFrame.lua:4302>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:

**Comment by Wuild** [comment]
please use the settings window for the addon instead by right clicking the minimap button or by going
menu -> interface -> addons -> gatherlite
