### ISSUE TITLE
Gatherlite sending LUA error on startup

### ISSUE THREAD

**Issue by 2damfresh** [Wuild/GatherLite#96]
Gatherlite throws a LUA error every login / reloadui.  

The message being sent on startup while gather lite is isolated is:

Message: Interface\AddOns\GatherLite\Locale\zhCN.lua:2: attempt to index local 'L' (a nil value)
Time: Thu Oct  3 19:31:55 2019
Count: 1
Stack: Interface\AddOns\GatherLite\Locale\zhCN.lua:2: attempt to index local 'L' (a nil value)
Interface\AddOns\GatherLite\Locale\zhCN.lua:2: in main chunk

Locals: L = nil
(*temporary) = <table> {
 apps = <table> {
 }
 GetLocale = <function> defined @Interface\AddOns\GatherLite\Libs\AceLocale-3.0\AceLocale-3.0.lua:132
 NewLocale = <function> defined @Interface\AddOns\GatherLite\Libs\AceLocale-3.0\AceLocale-3.0.lua:93
 appnames = <table> {
 }
}
(*temporary) = "GatherLite"
(*temporary) = "zhCN"
(*temporary) = "attempt to index local 'L' (a nil value)"

**Comment by Wuild** [comment]
I believe your using an older version of GatherLite, Please update your addon through curseforge or the twitch app. I'm not uploading this addon anywhere else and if you have gotten it from somewhere else i'm not the maintainer on that website. If this error still occures after updating your addon i will look into it once more.
