### ISSUE TITLE
Bad hang when opening map.

### ISSUE THREAD

**Issue by ZachM89** [Wuild/GatherLite#97]
**Describe the bug**
After marking herbalism nodes, the map takes progressively longer to open and causes your game to hang for almost a second sometimes when opening.

**To Reproduce**
1. Collect herbs
2. Open your map

**Expected behavior**
The map should open and not cause the game to lag or hang.

**Screenshots**

**Additional context**
The more herbs you mark, the longer the hang.

**Comment by Wuild** [comment]
I believe your using an older version of GatherLite, Please update your addon through curseforge or the twitch app. I'm not uploading this addon anywhere else and if you have gotten it from somewhere else i'm not the maintainer on that website. If this error still occures after updating your addon i will look into it once more.
