### ISSUE TITLE
Treasure not tracking?

### ISSUE THREAD

**Issue by 75338** [Wuild/GatherLite#98]
**Describe the bug**
Using Classic, not seeing treasure chests that I've opened on minimap or map.

**To Reproduce**
1. Enable GatherLite Classic
2. Open Solid Chest
3. Doesn't show on minimap or map.

**Expected behavior**
Should track just like regular mining/herb nodes?

Apologies if I missed something. Just signed up to GitHub to report this as I care about Treasure chests in wow... Please delete this issue if I'm wrong.

**Comment by Wuild** [comment]
This shouldnt be a problem. please check if you running the latest version from curseforge or the twitch app.
