### ISSUE TITLE
Icons always on Map

### ISSUE THREAD

**Issue by gonzalezman88** [Wuild/GatherLite#99]
I close the Map and the icons still apear on the playing screen. I deleted Gatherer and installed it again but the same problem.
![WoWScrnShot_100519_161124](https://user-images.githubusercontent.com/56197227/66256153-568c0c80-e78b-11e9-919f-0a37bfd7865a.jpg)

**Comment by Wuild** [comment]
I believe your using an older version of GatherLite, Please update your addon through curseforge or the twitch app. I'm not uploading this addon anywhere else and if you have gotten it from somewhere else i'm not the maintainer on that website. If this error still occures after updating your addon i will look into it once more.
